# Generated by Django 5.2.7 on 2025-10-18 14:10

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [migrations.AddField(
    model_name='questionattempt',
    name='question_part',
    field=models.ForeignKey(
        to='interactive_lessons.questionpart',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='attempts',
        help_text='Linked part of the question (if applicable)',
    ),
),

    ]
