# Generated by Django 5.2.7 on 2025-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_question_part_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='feedback',
            field=models.TextField(blank=True, help_text='Auto or teacher feedback text.'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='marks_awarded',
            field=models.FloatField(default=0, help_text='Actual marks earned for this attempt.'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='score_awarded',
            field=models.FloatField(default=0, help_text='Score percentage (0–100).'),
        ),
    ]
