# Generated by Django 5.2.7 on 2025-11-13 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_questionattempt_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Registration code for new signups', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can be used')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this code can be used (0 = unlimited)')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='How many times this code has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Class of 2025')", max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
