# Generated by Django 5.2.7 on 2025-11-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_loginhistory_usersession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='students_lo_timesta_653944_idx',
            old_name='students_lo_timesta_a1e2cd_idx',
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='students_lo_user_id_671a09_idx',
            old_name='students_lo_user_id_cb9d2f_idx',
        ),
    ]
