# Generated by Django 5.2.7 on 2026-01-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homeworknotificationsnooze'),
        ('students', '0006_rename_students_lo_timesta_a1e2cd_idx_students_lo_timesta_653944_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='code_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Type of account this code creates (student or teacher)', max_length=10),
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='teacher_class',
            field=models.ForeignKey(blank=True, help_text="If code_type='student', optionally link to a specific class for auto-enrollment", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_codes', to='homework.teacherclass'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='description',
            field=models.CharField(blank=True, help_text="Optional description (e.g., 'Class of 2025', 'Teacher Access 2025')", max_length=200),
        ),
    ]
