# Generated by Django 5.2.7 on 2026-01-15 22:05

from django.db import migrations


def create_user_groups(apps, schema_editor):
    """
    Create Students and Teachers groups and assign existing users.
    - Teachers group: users with is_staff=True
    - Students group: users with is_staff=False
    """
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')

    # Create groups
    students_group, _ = Group.objects.get_or_create(name='Students')
    teachers_group, _ = Group.objects.get_or_create(name='Teachers')

    # Assign existing users to appropriate groups
    for user in User.objects.all():
        if user.is_staff:
            user.groups.add(teachers_group)
        else:
            user.groups.add(students_group)


def reverse_groups(apps, schema_editor):
    """Remove the groups on migration rollback."""
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Students', 'Teachers']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_registration_code_types'),
    ]

    operations = [
        migrations.RunPython(create_user_groups, reverse_groups),
    ]
