# Generated by Django 5.2.7 on 2026-01-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_is_gaelscoil_school_secondary_contact_email_and_more'),
        ('students', '0008_setup_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this registration code belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_codes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this student belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.school'),
        ),
    ]
