# Generated by Django 5.2.7 on 2026-01-16 12:16

from django.db import migrations


def assign_rosary_college(apps, schema_editor):
    """
    Assign all existing students and teachers to Rosary College.
    Creates the school if it doesn't exist.
    """
    School = apps.get_model('schools', 'School')
    StudentProfile = apps.get_model('students', 'StudentProfile')
    TeacherProfile = apps.get_model('homework', 'TeacherProfile')

    # Get or create Rosary College
    rosary_college, created = School.objects.get_or_create(
        name='Rosary College',
        defaults={
            'address': 'Crumlin, Dublin 12',
            'email': 'info@rosarycollegedublin.ie',
            'principal_name': 'TBD',
            'county': 'Dublin',
            'school_type': 'secondary'
        }
    )

    if created:
        print(f"✓ Created Rosary College school")
    else:
        print(f"✓ Found existing Rosary College school")

    # Assign all students to Rosary College
    students_updated = StudentProfile.objects.filter(school__isnull=True).update(school=rosary_college)
    print(f"✓ Assigned {students_updated} students to Rosary College")

    # Assign all teachers to Rosary College
    teachers_updated = TeacherProfile.objects.filter(school__isnull=True).update(school=rosary_college)
    print(f"✓ Assigned {teachers_updated} teachers to Rosary College")


def reverse_assignment(apps, schema_editor):
    """
    Reverse operation: remove school assignments.
    """
    StudentProfile = apps.get_model('students', 'StudentProfile')
    TeacherProfile = apps.get_model('homework', 'TeacherProfile')

    StudentProfile.objects.all().update(school=None)
    TeacherProfile.objects.all().update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_registrationcode_school_studentprofile_school'),
        ('schools', '0001_initial'),  # Need schools app migration
        ('homework', '0003_teacherprofile_school_and_more'),  # Need homework migration
    ]

    operations = [
        migrations.RunPython(assign_rosary_college, reverse_assignment),
    ]
