# Generated by Django 5.2.7 on 2026-08-10 17:46

import django.db.models.deletion
import django.utils.timezone
import students.models
import students.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0020_remove_examquestion_suggested_time_minutes'),
        ('interactive_lessons', '0029_questionpart_solution_unlock_after_attempts'),
        ('students', '0012_questionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Private: served only via the work_photo view, never by URL.', storage=students.storage.PrivateStorage(), upload_to=students.models.work_photo_path)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting photo'), ('analysing', 'Analysing'), ('complete', 'Complete'), ('failed', 'Failed')], default='awaiting', max_length=12)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('transcription', models.TextField(blank=True)),
                ('method_feedback', models.TextField(blank=True)),
                ('diagram_feedback', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('has_diagram', models.BooleanField(default=False)),
                ('has_working', models.BooleanField(default=True)),
                ('readable', models.BooleanField(default=True)),
                ('confidence', models.CharField(blank=True, max_length=8)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exam_question_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='exam_papers.examquestionpart')),
                ('question_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='interactive_lessons.questionpart')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='students_wo_student_f31fb1_idx'), models.Index(fields=['status'], name='students_wo_status_cfc7e8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('exam_question_part__isnull', True), ('question_part__isnull', False)), models.Q(('exam_question_part__isnull', False), ('question_part__isnull', True)), _connector='OR'), name='worksubmission_exactly_one_part')],
            },
        ),
    ]
