# Generated by Django 5.2.7 on 2026-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_worksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksubmission',
            name='estimated_mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='estimated_max_marks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksubmission',
            name='mark_reasoning',
            field=models.TextField(blank=True),
        ),
    ]
