# Generated by Django 5.2.7 on 2026-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Subject name (e.g., 'Maths', 'Physics')", max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which subjects appear on homepage (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is available to students')),
                ('icon', models.CharField(blank=True, help_text="Icon class or emoji for subject (e.g., '📐', '⚡')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description shown on subject selection page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
