# Generated by Django 5.2.7 on 2026-01-26 20:13

from django.db import migrations


def seed_subjects(apps, schema_editor):
    """Create initial Maths and Physics subjects"""
    Subject = apps.get_model('core', 'Subject')

    # Create Maths subject (existing content)
    Subject.objects.get_or_create(
        slug='maths',
        defaults={
            'name': 'Maths',
            'display_order': 1,
            'is_active': True,
            'icon': '',
            'description': 'Leaving Certificate Higher Level Mathematics - Interactive lessons, exam papers, and practice questions.'
        }
    )

    # Create Physics subject (new)
    Subject.objects.get_or_create(
        slug='physics',
        defaults={
            'name': 'Physics',
            'display_order': 2,
            'is_active': True,
            'icon': '',
            'description': 'Leaving Certificate Higher Level Physics - Master concepts through interactive simulations and exam practice.'
        }
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded subjects if migration is reversed"""
    Subject = apps.get_model('core', 'Subject')
    Subject.objects.filter(slug__in=['maths', 'physics']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_subjects, reverse_seed),
    ]
