# Generated by Django 5.2.17 on 2026-09-20 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('exam_papers', '0023_exampartsolutionimage'),
        ('flashcards', '0003_flashcard_external_id'),
        ('homework', '0012_homeworktask_exam_question_part'),
        ('interactive_lessons', '0031_assign_topic_papers'),
        ('quickkicks', '0007_alter_quickkick_options_alter_quickkickview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(default=1, help_text='1 for the first attempt, 2 after a fail, and so on')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('ready', 'Ready to sit'), ('passed', 'Passed'), ('failed', 'Not passed'), ('voided', 'Voided by teacher')], default='locked', max_length=12)),
                ('pass_mark', models.PositiveSmallIntegerField(help_text='Percentage needed to pass, frozen when this checkpoint was set')),
                ('unlocked_at', models.DateTimeField(blank=True, help_text='Only work done after this counts towards the result', null=True)),
                ('sat_at', models.DateTimeField(blank=True, null=True)),
                ('marks_awarded', models.FloatField(blank=True, null=True)),
                ('marks_possible', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, help_text='Percentage, 0-100', null=True)),
                ('is_clean', models.BooleanField(default=True, help_text='False if a marking scheme was opened while sitting this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Plan Checkpoint',
                'ordering': ['goal', 'round'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('weekly_minutes', models.PositiveSmallIntegerField(default=120, help_text='Minutes of work per week this student has committed to', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1200)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='The nightly run leaves a locked plan exactly as it is')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_template', models.ForeignKey(blank=True, help_text='The plan this one was generated from during a class rollout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollouts', to='studyplans.studyplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='core.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher who set this plan', on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='homework.teacherprofile')),
                ('teacher_class', models.ForeignKey(blank=True, help_text='Class this plan was rolled out to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='homework.teacherclass')),
            ],
            options={
                'verbose_name': 'Study Plan',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanCheckpointPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('marks_possible', models.PositiveSmallIntegerField()),
                ('marks_awarded', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('hint_used', models.BooleanField(default=False)),
                ('solution_viewed', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='studyplans.studyplancheckpoint')),
                ('exam_question_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_parts', to='exam_papers.examquestionpart')),
            ],
            options={
                'verbose_name': 'Study Plan Checkpoint Part',
                'ordering': ['checkpoint', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_mastery', models.PositiveSmallIntegerField(default=75, help_text='Percentage on the checkpoint that counts as mastered', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('checkpoint_size', models.PositiveSmallIntegerField(default=3, help_text='How many exam parts make up each checkpoint', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'High'), (3, 'Critical')], default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('needs_teacher_attention', models.BooleanField(default=False)),
                ('attention_reason', models.CharField(blank=True, max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='studyplans.studyplan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plan_goals', to='interactive_lessons.topic')),
            ],
            options={
                'verbose_name': 'Study Plan Goal',
                'ordering': ['plan', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='studyplancheckpoint',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='studyplans.studyplangoal'),
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('exam_part', 'Exam Question Part'), ('quickkick', 'QuickFlicks Video/Applet'), ('flashcard', 'Flashcard Set'), ('custom', 'Written Exercise')], max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('origin', models.CharField(choices=[('generated', 'Generated'), ('teacher', 'Chosen by teacher'), ('revisit', 'Revisit after a checkpoint')], default='generated', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Not started'), ('attempted', 'Started'), ('done', 'Done'), ('skipped', 'No longer needed')], default='pending', max_length=12)),
                ('available_from', models.DateField()),
                ('due_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_score', models.FloatField(blank=True, null=True)),
                ('evidence_note', models.CharField(blank=True, help_text='Why this counted as done, in words the student can read', max_length=200)),
                ('carried_over_count', models.PositiveSmallIntegerField(default=0)),
                ('needs_teacher_attention', models.BooleanField(default=False)),
                ('student_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='exam_papers.examquestion')),
                ('exam_question_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='exam_papers.examquestionpart')),
                ('flashcard_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='flashcards.flashcardset')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='studyplans.studyplangoal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studyplans.studyplan')),
                ('quickkick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='quickkicks.quickkick', verbose_name='QuickFlicks')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='interactive_lessons.section')),
            ],
            options={
                'verbose_name': 'Study Plan Item',
                'ordering': ['plan', 'week', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Plan created'), ('rollout', 'Rolled out to a class'), ('carried', 'Work carried forward'), ('injected', 'Extra work added'), ('checkpoint_unlocked', 'Checkpoint unlocked'), ('checkpoint_passed', 'Checkpoint passed'), ('checkpoint_failed', 'Checkpoint not passed'), ('goal_mastered', 'Topic mastered'), ('teacher_edit', 'Teacher edited the plan'), ('attention', 'Needs the teacher')], max_length=24)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='studyplans.studyplancheckpoint')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studyplans.studyplan')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='studyplans.studyplanitem')),
            ],
            options={
                'verbose_name': 'Study Plan Event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='1 for the first week')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('minutes_budget', models.PositiveSmallIntegerField()),
                ('focus_note', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='studyplans.studyplan')),
            ],
            options={
                'verbose_name': 'Study Plan Week',
                'ordering': ['plan', 'index'],
            },
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Empty means backlog', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studyplans.studyplanweek'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['student', 'status'], name='studyplans__student_c6e91c_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['status', 'deadline'], name='studyplans__status_78578c_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__gte', models.F('start_date'))), name='studyplan_deadline_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('source_template__isnull', False)), fields=('student', 'source_template'), name='studyplan_one_rollout_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studyplancheckpointpart',
            constraint=models.UniqueConstraint(fields=('checkpoint', 'exam_question_part'), name='studyplancheckpointpart_once_per_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='studyplangoal',
            constraint=models.UniqueConstraint(fields=('plan', 'topic'), name='studyplangoal_one_per_topic'),
        ),
        migrations.AddIndex(
            model_name='studyplancheckpoint',
            index=models.Index(fields=['goal', 'status'], name='studyplans__goal_id_246419_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplancheckpoint',
            constraint=models.UniqueConstraint(fields=('goal', 'round'), name='studyplancheckpoint_one_per_round'),
        ),
        migrations.AddIndex(
            model_name='studyplanevent',
            index=models.Index(fields=['plan', '-created_at'], name='studyplans__plan_id_66bb01_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplanweek',
            constraint=models.UniqueConstraint(fields=('plan', 'index'), name='studyplanweek_index_per_plan'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['plan', 'status'], name='studyplans__plan_id_8eb18a_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanitem',
            index=models.Index(fields=['week', 'order'], name='studyplans__week_id_091925_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('available_from'))), name='studyplanitem_due_after_available'),
        ),
    ]
