# Generated by Django 5.2.17 on 2026-09-20 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('homework', '0012_homeworktask_exam_question_part'),
        ('studyplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyplan',
            name='studyplan_one_rollout_per_student',
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(fields=('student', 'source_template'), name='studyplan_one_rollout_per_student'),
        ),
    ]
