# Generated by Django 5.2.17 on 2026-09-20 17:33

from django.conf import settings
from django.db import migrations, models


def fill_active_slots(apps, schema_editor):
    """Backfill the sentinel, keeping one active plan per student.

    Without this the new column stays NULL on rows that already exist, so the
    unique index would be satisfied by every one of them and the rule would
    only start applying to plans saved afterwards.

    Where a student already has more than one active plan, the most recently
    started one is kept and the others are archived rather than deleted -- a
    plan carries a student's work, so nothing here throws any of it away.
    """
    StudyPlan = apps.get_model('studyplans', 'StudyPlan')
    seen = set()
    for plan in (StudyPlan.objects.filter(status='active')
                 .order_by('student_id', '-start_date', '-id')):
        if plan.student_id in seen:
            plan.status = 'archived'
            plan.active_slot = None
        else:
            seen.add(plan.student_id)
            plan.active_slot = plan.student_id
        plan.save(update_fields=['status', 'active_slot'])


def clear_active_slots(apps, schema_editor):
    """Reversing only drops the sentinel; archived plans stay archived."""
    StudyPlan = apps.get_model('studyplans', 'StudyPlan')
    StudyPlan.objects.update(active_slot=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('homework', '0012_homeworktask_exam_question_part'),
        ('studyplans', '0002_rollout_constraint_without_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='active_slot',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Internal: enforces one active plan per student', null=True),
        ),
        migrations.RunPython(fill_active_slots, clear_active_slots),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(fields=('active_slot',), name='studyplan_one_active_per_student'),
        ),
    ]
