# Generated by Django 5.2.17 on 2026-09-21 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0031_assign_topic_papers'),
        ('studyplans', '0003_one_active_plan_per_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicStampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microstamps', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stamp_cards', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_cards', to='interactive_lessons.topic')),
            ],
            options={
                'verbose_name': 'Topic Stamp Card',
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='topicstampcard_one_per_topic')],
            },
        ),
    ]
