# Generated by Django 5.2.17 on 2026-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplans', '0004_topic_stamp_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplancheckpointpart',
            name='marked_from_photo',
            field=models.BooleanField(default=False, help_text='The mark came from a photo of the working, not a typed answer'),
        ),
    ]
