# Generated by Django 5.2.17 on 2026-09-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplans', '0005_checkpoint_part_from_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Plan created'), ('rollout', 'Rolled out to a class'), ('carried', 'Work carried forward'), ('injected', 'Extra work added'), ('microbadge_earned', 'MicroBadge earned'), ('checkpoint_unlocked', 'Badge Test opened'), ('checkpoint_passed', 'Badge Test passed'), ('checkpoint_failed', 'Badge Test not passed'), ('goal_mastered', 'Topic mastered'), ('teacher_edit', 'Teacher edited the plan'), ('attention', 'Needs the teacher')], max_length=24),
        ),
        migrations.CreateModel(
            name='StudyPlanMicroBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='1-10 core, 11 on for retries')),
                ('kind', models.CharField(choices=[('core', 'MicroBadge'), ('retry', 'Retry MicroBadge')], default='core', max_length=6)),
                ('target_date', models.DateField(help_text='When it should be earned by to finish on time -- a pace, not a lock')),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('earned_by_teacher', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_badges', to='studyplans.studyplangoal')),
            ],
            options={
                'verbose_name': 'MicroBadge',
                'ordering': ['goal', 'number'],
            },
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='micro_badge',
            field=models.ForeignKey(blank=True, help_text='The MicroBadge this counts towards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='studyplans.studyplanmicrobadge'),
        ),
        migrations.DeleteModel(
            name='TopicStampCard',
        ),
        migrations.AddConstraint(
            model_name='studyplanmicrobadge',
            constraint=models.UniqueConstraint(fields=('goal', 'number'), name='microbadge_number_per_goal'),
        ),
    ]
