# Generated by Django 5.2.17 on 2026-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplans', '0007_weeks_into_microbadges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Plan created'), ('rollout', 'Rolled out to a class'), ('carried', 'Work carried forward'), ('injected', 'Extra work added'), ('microbadge_earned', 'MicroBadge earned'), ('checkpoint_unlocked', 'Badge Test opened'), ('checkpoint_passed', 'Badge Test passed'), ('checkpoint_failed', 'Badge Test not passed'), ('goal_mastered', 'Topic mastered'), ('teacher_edit', 'Teacher edited the plan'), ('attention', 'Needs the teacher'), ('notified', 'Student emailed')], max_length=24),
        ),
    ]
