# Generated by Django 5.2.17 on 2026-10-04 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplans', '0008_event_kind_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplangoal',
            name='checkpoint_size',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many whole exam questions make up each checkpoint', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
