# Generated by Django 5.2.7 on 2025-11-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_lessons', '0017_link_questions_to_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the exam (e.g., 2024)')),
                ('paper_type', models.CharField(choices=[('p1', 'Paper 1'), ('p2', 'Paper 2')], help_text='Paper 1 or Paper 2', max_length=10)),
                ('title', models.CharField(help_text="Display title (e.g., 'Leaving Certificate 2024 Paper 1')", max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('time_limit_minutes', models.IntegerField(default=150, help_text='Total time allowed for this paper in minutes')),
                ('total_marks', models.IntegerField(help_text='Total marks available on this paper')),
                ('instructions', models.TextField(blank=True, help_text="General instructions for the paper (e.g., 'Answer 6 out of 8 questions')")),
                ('source_pdf', models.FileField(blank=True, help_text='Original exam paper PDF', null=True, upload_to='exam_papers/pdfs/')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this paper is visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'paper_type'],
                'unique_together': {('year', 'paper_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_mode', models.CharField(choices=[('full_timed', 'Full Paper - Timed'), ('full_practice', 'Full Paper - Practice'), ('question_practice', 'Individual Question Practice')], default='question_practice', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Total time spent on this attempt')),
                ('total_marks_awarded', models.FloatField(default=0.0)),
                ('total_marks_possible', models.FloatField(default=0.0)),
                ('percentage_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False, help_text='True if student submitted the exam (for timed mode)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_papers.exampaper')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Question number on the paper (e.g., 1, 2, 3)')),
                ('title', models.CharField(blank=True, help_text='Optional title/description of the question', max_length=255)),
                ('stem', models.TextField(blank=True, help_text='Question stem/introduction (shared by all parts)')),
                ('image', models.ImageField(blank=True, help_text='Diagram or image for the question stem', null=True, upload_to='exam_papers/questions/')),
                ('suggested_time_minutes', models.IntegerField(blank=True, help_text='Suggested time for this question in minutes', null=True)),
                ('total_marks', models.IntegerField(help_text='Total marks for this question (sum of all parts)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the paper')),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_papers.exampaper')),
                ('topic', models.ForeignKey(blank=True, help_text='Topic this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='interactive_lessons.topic')),
            ],
            options={
                'ordering': ['exam_paper', 'order', 'question_number'],
                'unique_together': {('exam_paper', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Part label (e.g., '(a)', '(b)', '(i)', '(ii)')", max_length=10)),
                ('prompt', models.TextField(help_text='The actual question text for this part')),
                ('image', models.ImageField(blank=True, help_text='Diagram or image specific to this part', null=True, upload_to='exam_papers/question_parts/')),
                ('answer', models.TextField(help_text='Correct answer (or acceptable answers separated by |)')),
                ('expected_format', models.TextField(blank=True, help_text='Description of expected answer format for students')),
                ('expected_type', models.CharField(choices=[('exact', 'Exact match'), ('numeric', 'Numeric with tolerance'), ('expression', 'Algebraic Expression'), ('multi', 'Multiple choice'), ('manual', 'Manual grading required')], default='exact', max_length=20)),
                ('solution', models.TextField(blank=True, help_text='Worked solution for this part')),
                ('solution_image', models.ImageField(blank=True, help_text='Solution diagram or image', null=True, upload_to='exam_papers/solutions/')),
                ('solution_unlock_after_attempts', models.PositiveIntegerField(default=2, help_text='Number of attempts before solution becomes visible (0 = always visible)')),
                ('max_marks', models.IntegerField(help_text='Marks available for this part')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='exam_papers.examquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('max_marks', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, help_text='Automated or manual feedback')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt is this (1st, 2nd, 3rd, etc.)')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this specific question part')),
                ('hint_used', models.BooleanField(default=False)),
                ('solution_viewed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='exam_papers.examattempt')),
                ('question_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam_papers.examquestionpart')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_breakdown', models.JSONField(help_text='\n        Structured marking scheme. Example:\n        {\n            "steps": [\n                {"description": "Identify correct formula", "marks": 1},\n                {"description": "Substitute values correctly", "marks": 1},\n                {"description": "Simplify to final answer", "marks": 2}\n            ],\n            "common_errors": [\n                "Forgetting to convert degrees to radians",\n                "Sign error in quadrant determination"\n            ],\n            "partial_credit_notes": "Award 1 mark for correct approach even if arithmetic error"\n        }\n        ')),
                ('examiner_notes', models.TextField(blank=True, help_text='Additional notes from marking scheme or examiners')),
                ('national_mean_score', models.FloatField(blank=True, help_text='National average score for this question part (percentage)', null=True)),
                ('question_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_scheme', to='exam_papers.examquestionpart')),
            ],
            options={
                'verbose_name': 'Marking Scheme',
                'verbose_name_plural': 'Marking Schemes',
            },
        ),
    ]
