# Generated by Django 5.2.7 on 2025-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='marking_scheme_pdf',
            field=models.FileField(blank=True, help_text='Official marking scheme PDF for this paper', null=True, upload_to='exam_papers/marking_schemes/pdfs/'),
        ),
    ]
