# Generated by Django 5.2.7 on 2025-11-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0002_exampaper_marking_scheme_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkingScheme',
        ),
    ]
