# Generated by Django 5.2.7 on 2025-11-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0003_delete_markingscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFormatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short name for this format (e.g., 'Degrees', 'Exact Fraction')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='The format instruction shown to students')),
                ('example', models.CharField(blank=True, help_text="Example answer in this format (e.g., '45°' or '3/4')", max_length=200)),
                ('category', models.CharField(blank=True, help_text="Category for grouping (e.g., 'Angles', 'Fractions', 'Algebra')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for selection')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in dropdown')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='examquestionpart',
            name='expected_format',
            field=models.TextField(blank=True, help_text='Custom format description (or leave blank to use template)'),
        ),
        migrations.AddField(
            model_name='examquestionpart',
            name='answer_format_template',
            field=models.ForeignKey(blank=True, help_text='Select a predefined answer format template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_papers.answerformattemplate'),
        ),
    ]
