# Generated by Django 5.2.7 on 2025-11-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0003_delete_markingscheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='stem',
        ),
    ]
