# Generated by Django - placeholder migration
# This migration was applied on PythonAnywhere but the file was missing locally

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0005_remove_examquestion_stem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestionpart',
            name='prompt',
        ),
    ]