# Generated by Django 5.2.7 on 2025-12-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0005_remove_examquestion_stem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestionpart',
            name='prompt',
        ),
    ]
