# Generated by Django 5.2.7 on 2025-12-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_papers", "0004_answerformattemplate_and_more"),
        (
            "exam_papers",
            "0006_answerformattemplate_remove_examquestionpart_prompt_and_more",
        ),
        ("exam_papers", "0006_remove_examquestionpart_prompt"),
    ]

    operations = []
