# Generated by Django 5.2.7 on 2025-12-29 18:49

from django.db import migrations, models, connection


def check_and_remove_fields(apps, schema_editor):
    """
    Safely remove fields only if they exist in the database.
    This handles cases where production database schema differs from dev.
    """
    with connection.cursor() as cursor:
        # Check which columns exist
        cursor.execute("""
            SELECT COLUMN_NAME
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'exam_papers_examquestionpart'
            AND COLUMN_NAME IN ('answer_format_template_id', 'answer', 'expected_format', 'expected_type', 'solution')
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Only drop columns that exist
        table_name = 'exam_papers_examquestionpart'

        if 'answer_format_template_id' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN answer_format_template_id")

        if 'answer' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN answer")

        if 'expected_format' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN expected_format")

        if 'expected_type' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN expected_type")

        if 'solution' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN solution")


def delete_answer_format_template_table(apps, schema_editor):
    """
    Delete AnswerFormatTemplate table if it exists.
    """
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'exam_papers_answerformattemplate'
        """)
        table_exists = cursor.fetchone()[0] > 0

        if table_exists:
            cursor.execute("DROP TABLE exam_papers_answerformattemplate")


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0009_fix_utf8mb4_encoding'),
        ('interactive_lessons', '0021_remove_answer_format_template'),
    ]

    operations = [
        # Use RunPython to conditionally drop fields
        migrations.RunPython(
            check_and_remove_fields,
            reverse_code=migrations.RunPython.noop
        ),

        # Update field definitions
        migrations.AlterField(
            model_name='examquestionpart',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Marking scheme image - used by GPT-4 Vision for grading', null=True, upload_to='exam_papers/marking_schemes/'),
        ),
        migrations.AlterField(
            model_name='examquestionpart',
            name='solution_unlock_after_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Number of attempts before marking scheme becomes visible (0 = always visible)'),
        ),

        # Delete AnswerFormatTemplate table if it exists
        migrations.RunPython(
            delete_answer_format_template_table,
            reverse_code=migrations.RunPython.noop
        ),
    ]
