# Generated by Django 5.2.7 on 2025-12-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0009_fix_utf8mb4_encoding'),
        ('interactive_lessons', '0020_question_is_quickkick_suitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestionpart',
            name='answer_format_template',
        ),
        migrations.RemoveField(
            model_name='examquestionpart',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='examquestionpart',
            name='expected_format',
        ),
        migrations.RemoveField(
            model_name='examquestionpart',
            name='expected_type',
        ),
        migrations.RemoveField(
            model_name='examquestionpart',
            name='solution',
        ),
        migrations.AlterField(
            model_name='examquestionpart',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Marking scheme image - used by GPT-4 Vision for grading', null=True, upload_to='exam_papers/marking_schemes/'),
        ),
        migrations.AlterField(
            model_name='examquestionpart',
            name='solution_unlock_after_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Number of attempts before marking scheme becomes visible (0 = always visible)'),
        ),
        migrations.DeleteModel(
            name='AnswerFormatTemplate',
        ),
    ]
