# Generated by Django 5.2.7 on 2025-12-30 11:10

from django.db import migrations, models, connection


def remove_fields_if_exist(apps, schema_editor):
    """
    Safely remove fields only if they exist in the database.
    This handles cases where migration 0010 already removed these fields.
    """
    with connection.cursor() as cursor:
        # Check which columns exist
        cursor.execute("""
            SELECT COLUMN_NAME
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'exam_papers_examquestionpart'
            AND COLUMN_NAME IN ('answer_format_template_id', 'answer', 'expected_format', 'expected_type', 'image', 'solution')
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}

        # Only drop columns that exist
        table_name = 'exam_papers_examquestionpart'

        if 'answer_format_template_id' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN answer_format_template_id")

        if 'answer' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN answer")

        if 'expected_format' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN expected_format")

        if 'expected_type' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN expected_type")

        if 'image' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN image")

        if 'solution' in existing_columns:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN solution")


def delete_answer_format_template_if_exists(apps, schema_editor):
    """
    Delete AnswerFormatTemplate table if it exists.
    """
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'exam_papers_answerformattemplate'
        """)
        table_exists = cursor.fetchone()[0] > 0

        if table_exists:
            cursor.execute("DROP TABLE exam_papers_answerformattemplate")


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0010_remove_answer_fields'),
    ]

    operations = [
        # Safely remove fields that might have been already removed
        migrations.RunPython(
            remove_fields_if_exist,
            reverse_code=migrations.RunPython.noop
        ),

        # Make max_marks nullable
        migrations.AlterField(
            model_name='examquestionpart',
            name='max_marks',
            field=models.IntegerField(blank=True, help_text='Maximum marks for this part (leave blank to auto-extract from marking scheme image)', null=True),
        ),

        # Update solution_image help text
        migrations.AlterField(
            model_name='examquestionpart',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Marking scheme image - used by GPT-4 Vision for grading and extracting max marks', null=True, upload_to='exam_papers/marking_schemes/'),
        ),

        # Delete AnswerFormatTemplate table if it exists
        migrations.RunPython(
            delete_answer_format_template_if_exists,
            reverse_code=migrations.RunPython.noop
        ),
    ]
