# Generated by Django 5.2.7 on 2026-01-09 18:20

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = %s
            AND COLUMN_NAME = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def safe_remove_field(apps, schema_editor, model_name, field_name, table_name):
    """Safely remove a field only if it exists"""
    if check_column_exists(table_name, field_name):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {field_name}")


def safe_remove_fields(apps, schema_editor):
    """Remove old fields only if they exist"""
    fields_to_check = [
        ('answer_format_template_id', 'exam_papers_examquestionpart'),
        ('answer', 'exam_papers_examquestionpart'),
        ('expected_format', 'exam_papers_examquestionpart'),
        ('expected_type', 'exam_papers_examquestionpart'),
        ('image', 'exam_papers_examquestionpart'),
        ('solution', 'exam_papers_examquestionpart'),
    ]

    for field_name, table_name in fields_to_check:
        safe_remove_field(apps, schema_editor, 'examquestionpart', field_name, table_name)


def reverse_safe_remove(apps, schema_editor):
    """Reverse migration - do nothing as we can't reliably restore removed fields"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0012_safe_remove_answer_format_template'),
    ]

    operations = [
        # First add the new field
        migrations.AddField(
            model_name='exampaper',
            name='is_deferred',
            field=models.BooleanField(default=False, help_text='Is this a deferred exam paper?'),
        ),
        # Update model options
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-year', 'paper_type', 'is_deferred']},
        ),
        # Clear old unique_together before setting new one
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together=set(),
        ),
        # Set new unique_together
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('year', 'paper_type', 'is_deferred')},
        ),
        # Safely remove old fields using Python function
        migrations.RunPython(safe_remove_fields, reverse_safe_remove),
    ]
