# Generated by Django 5.2.7 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0012_safe_remove_answer_format_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-year', 'paper_type', 'is_deferred']},
        ),
        migrations.AddField(
            model_name='exampaper',
            name='is_deferred',
            field=models.BooleanField(default=False, help_text='Is this a deferred exam paper?'),
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('year', 'paper_type', 'is_deferred')},
        ),
    ]