# Generated by Django 5.2.7 on 2026-01-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0013_remove_examquestionpart_answer_format_template_and_more'),
        ('exam_papers', '0014_alter_exampaper_options_and_more'),
    ]

    operations = [
    ]
