# Generated by Django 5.2.7 on 2026-01-23 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0016_remove_examquestionpart_fields_state_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Thumbs Up'), ('not_helpful', 'Thumbs Down')], help_text='Whether student found feedback helpful or not', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(help_text='The exam question attempt this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='exam_papers.examquestionattempt')),
                ('user', models.ForeignKey(help_text='Student who provided feedback', on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Question Feedback',
                'verbose_name_plural': 'Exam Question Feedback',
                'unique_together': {('attempt', 'user')},
            },
        ),
    ]
