# Generated by Django 5.2.7 on 2026-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0017_examquestionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Whether the exam is currently paused'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When the exam was paused', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_paused_seconds',
            field=models.IntegerField(default=0, help_text='Total time the exam has been paused (to calculate accurate time remaining)'),
        ),
    ]
