# Generated by Django 5.2.7 on 2026-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('exam_papers', '0018_examattempt_is_paused_examattempt_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this exam paper belongs to (Maths, Physics, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='core.subject'),
        ),
    ]
