# Generated by Django 5.2.7 on 2026-08-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0019_exampaper_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='suggested_time_minutes',
        ),
    ]
