# Generated by Django 5.2.17 on 2026-09-17 17:01

from django.db import migrations, models


def copy_question_topic_to_parts(apps, schema_editor):
    """Seed each part with its question's topic, so no question drops off a
    topic page before the parts are classified. Parts already tagged are left
    alone, which also makes this safe to run twice."""
    ExamQuestionPart = apps.get_model('exam_papers', 'ExamQuestionPart')
    parts = (ExamQuestionPart.objects
             .filter(question__topic__isnull=False, topics__isnull=True)
             .select_related('question'))
    for part in parts:
        part.topics.add(part.question.topic_id)


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0020_remove_examquestion_suggested_time_minutes'),
        ('interactive_lessons', '0031_assign_topic_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionpart',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Every topic this part draws on', related_name='exam_question_parts', to='interactive_lessons.topic'),
        ),
        migrations.RunPython(copy_question_topic_to_parts, migrations.RunPython.noop),
    ]
