# Generated by Django 5.2.17 on 2026-10-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0023_exampartsolutionimage'),
        ('interactive_lessons', '0031_assign_topic_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='list_under_secondary',
            field=models.BooleanField(default=False, help_text='Also list this question under its secondary topic'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='need_to_know_topic',
            field=models.ForeignKey(blank=True, help_text='A topic that plays a minor part; shown, never listed under', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='need_to_know_exam_questions', to='interactive_lessons.topic'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='secondary_topic',
            field=models.ForeignKey(blank=True, help_text='A second significant topic in this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_exam_questions', to='interactive_lessons.topic'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic this question is mainly about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='interactive_lessons.topic', verbose_name='Main topic'),
        ),
    ]
