# Generated by Django 5.2.17 on 2026-10-04 21:32

from django.db import migrations


def refuse_if_crops_remain(apps, schema_editor):
    """Dropping the table would throw away marking-scheme crops still in use.

    A part's scheme is one image now. Any row left here is a crop that was
    never folded into its part's solution_image, which flatten_solution_images
    (removed with this migration, in fe65a6e0) existed to do -- so stop rather
    than lose it, and fold it first with that commit checked out.
    """
    ExamPartSolutionImage = apps.get_model('exam_papers', 'ExamPartSolutionImage')
    remaining = ExamPartSolutionImage.objects.count()
    if remaining:
        raise RuntimeError(
            f'{remaining} stacked marking-scheme crop(s) still exist. Fold them '
            'into their parts with flatten_solution_images --recut --apply '
            '(commit fe65a6e0) before running this migration.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0025_seed_question_topics'),
    ]

    operations = [
        migrations.RunPython(refuse_if_crops_remain, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ExamPartSolutionImage',
        ),
    ]
