# Generated by Django 5.2.7 on 2025-10-18 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic_slug', models.SlugField(blank=True, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, help_text='Comma-separated list of retrieved note titles')),
                ('source_type', models.CharField(choices=[('notes', 'Notes'), ('ai', 'AI Generated'), ('mixed', 'Mixed')], default='ai', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('metadata', models.TextField(blank=True, help_text='Sample prompts or summary for embedding', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('_content_hash', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('topic', models.ForeignKey(blank=True, help_text='Select topic from interactive lessons', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='interactive_lessons.topic')),
            ],
        ),
    ]
