# Generated by Django 5.2.7 on 2025-11-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.CharField(choices=[('general', 'General Note'), ('exam_paper', 'Exam Paper'), ('marking_scheme', 'Marking Scheme')], default='general', help_text='Type of content (general note, exam paper, or marking scheme)', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='exam_year',
            field=models.IntegerField(blank=True, help_text='Year of the exam (e.g., 2024)', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID for source document', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='gdrive_link',
            field=models.URLField(blank=True, help_text='Public link to Google Drive file', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('p1', 'Paper 1'), ('p2', 'Paper 2')], help_text='Paper 1 or Paper 2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='question_number',
            field=models.CharField(blank=True, help_text="Specific question number or range (e.g., 'Q1', 'Q3(a)', '1-3')", max_length=20, null=True),
        ),
    ]
