# Generated by Django 5.2.7 on 2025-11-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_content_type_note_exam_year_note_gdrive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, help_text='Upload PDF or image file', null=True, upload_to='notes/'),
        ),
    ]
