# Generated by Django 5.2.7 on 2025-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobotquery',
            name='exam_question_id',
            field=models.IntegerField(blank=True, help_text='ID of exam_papers.ExamQuestion if query relates to an exam question', null=True),
        ),
        migrations.AddField(
            model_name='infobotquery',
            name='practice_question_id',
            field=models.IntegerField(blank=True, help_text='ID of interactive_lessons.Question if query relates to a practice question', null=True),
        ),
        migrations.AddField(
            model_name='infobotquery',
            name='question_context',
            field=models.TextField(blank=True, help_text='Stored question text for context (in case question is later modified/deleted)', null=True),
        ),
        migrations.AddField(
            model_name='infobotquery',
            name='question_part_id',
            field=models.IntegerField(blank=True, help_text='ID of QuestionPart or ExamQuestionPart being worked on', null=True),
        ),
    ]
