# Generated by Django 5.2.7 on 2026-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_infobotfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('student', 'Students'), ('teacher', 'Teachers')], default='all', help_text='Only used for Site Help notes: who this note is written for', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_type',
            field=models.CharField(choices=[('general', 'General Note'), ('exam_paper', 'Exam Paper'), ('marking_scheme', 'Marking Scheme'), ('site_help', 'Site Help')], default='general', help_text='Type of content (general note, exam paper, or marking scheme)', max_length=20),
        ),
    ]
