# Generated by Django 5.2.17 on 2026-09-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_audience_alter_note_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infobotquery',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Who asked. Blank for questions asked before this was recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infobot_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
