# Generated by Django 5.2.7 on 2026-07-27 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0010_add_notification_sent_to_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('behaviour', 'Behaviour'), ('test', 'Test')], max_length=20)),
                ('tone', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('concern', 'Concern')], default='neutral', max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('homework_due', models.BooleanField(default=True, help_text="Untick when no homework was set for this session, so the day doesn't count against homework rates")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='homework.teacherclass')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='homework.teacherclass')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('homework', models.CharField(choices=[('done', 'Done'), ('partial', 'Partial'), ('not_done', 'Not done')], default='done', max_length=10)),
                ('comment_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_preset', models.ForeignKey(blank=True, limit_choices_to={'category': 'behaviour'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_records', to='reports.commentpreset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reports.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('comment_text', models.CharField(blank=True, max_length=300)),
                ('comment_preset', models.ForeignKey(blank=True, limit_choices_to={'category': 'test'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='reports.commentpreset')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.classtest')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('label', models.CharField(blank=True, help_text="e.g. 'Period 3' or a room number", max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='homework.teacherclass')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='reports.timetableslot'),
        ),
        migrations.AddIndex(
            model_name='classtest',
            index=models.Index(fields=['teacher_class', '-date'], name='reports_cla_teacher_e9b6ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentsessionrecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_record_session_student'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='uniq_result_test_student'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['teacher_class', '-date'], name='reports_cla_teacher_9f146f_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('teacher_class', 'date', 'slot'), name='uniq_session_class_date_slot'),
        ),
    ]
