# Generated by Django 5.2.17 on 2026-09-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_studentclassnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
    ]
