# Generated by Django 5.2.17 on 2026-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_timetableslot_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionrecord',
            name='attendance',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsessionrecord',
            name='homework',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('partial', 'Partial'), ('not_done', 'Not done')], default='', max_length=10),
        ),
    ]
