# Generated by Django 5.2.17 on 2026-09-26 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_blank_attendance_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='OpenAI in dollars; Gemini in the currency Google charges the credit in', max_digits=10)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('spend_already_counted', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=12)),
                ('recorded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
            },
        ),
    ]
