from django.contrib import admin
from django.utils.html import format_html
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Count, Avg, Q
from datetime import timedelta
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from .models import StudentProfile, QuestionAttempt, RegistrationCode, LoginHistory, UserSession


@admin.register(StudentProfile)
class StudentProfileAdmin(admin.ModelAdmin):
    list_display = ('user', 'total_score', 'lessons_completed', 'last_activity')
    search_fields = ('user__username', 'user__email')
    readonly_fields = ('last_activity',)
    actions = ['generate_daily_report', 'generate_weekly_report', 'generate_monthly_report', 'generate_yearly_report', 'generate_all_attempts_report', 'generate_weekly_attempts_report']

    def _generate_report(self, request, queryset, days=1):
        """Helper method to generate activity report as PDF"""
        # Calculate date range
        end_date = timezone.now()
        start_date = end_date - timedelta(days=days)

        # Get attempts in the date range, excluding the admin user
        attempts_in_period = QuestionAttempt.objects.filter(
            attempted_at__gte=start_date,
            attempted_at__lte=end_date
        ).exclude(student__user=request.user)

        # If specific students selected, filter to those
        if queryset.exists():
            attempts_in_period = attempts_in_period.filter(student__in=queryset)

        # Overall statistics
        total_attempts = attempts_in_period.count()
        correct_attempts = attempts_in_period.filter(is_correct=True).count()
        accuracy = (correct_attempts / total_attempts * 100) if total_attempts > 0 else 0

        # Topics worked on
        topics_data = attempts_in_period.values(
            'question__topic__name'
        ).annotate(
            attempt_count=Count('id'),
            correct_count=Count('id', filter=Q(is_correct=True)),
            avg_score=Avg('score_awarded')
        ).order_by('-attempt_count')

        # Unique questions
        unique_questions = attempts_in_period.values('question__id').distinct().count()

        # Per-student breakdown
        student_stats = []
        students_to_report = queryset if queryset.exists() else StudentProfile.objects.exclude(user=request.user)

        for student in students_to_report:
            student_attempts = attempts_in_period.filter(student=student)
            attempt_count = student_attempts.count()

            if attempt_count > 0:
                correct_count = student_attempts.filter(is_correct=True).count()
                student_accuracy = (correct_count / attempt_count * 100) if attempt_count > 0 else 0
                avg_score = student_attempts.aggregate(Avg('score_awarded'))['score_awarded__avg'] or 0

                student_topics = student_attempts.values(
                    'question__topic__name'
                ).annotate(count=Count('id')).order_by('-count')

                student_stats.append({
                    'username': student.user.username,
                    'full_name': student.user.get_full_name() or student.user.username,
                    'attempt_count': attempt_count,
                    'correct_count': correct_count,
                    'accuracy': student_accuracy,
                    'avg_score': avg_score,
                    'topics': list(student_topics),
                    'total_score': student.total_score,
                    'lessons_completed': student.lessons_completed,
                })

        student_stats.sort(key=lambda x: x['attempt_count'], reverse=True)

        # Generate PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=16, textColor=colors.HexColor('#1f4788'), alignment=TA_CENTER)
        heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#1f4788'))

        # Title
        story.append(Paragraph(f'STUDENT ACTIVITY REPORT ({days} DAY{"S" if days > 1 else ""})', title_style))
        story.append(Spacer(1, 0.2*inch))

        # Metadata
        meta_data = [
            ['Period:', f"{start_date.strftime('%Y-%m-%d %H:%M')} to {end_date.strftime('%Y-%m-%d %H:%M')}"],
            ['Generated by:', request.user.username],
            ['Generated at:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')],
        ]
        if queryset.exists():
            meta_data.append(['Filtered to:', f'{queryset.count()} selected student(s)'])

        meta_table = Table(meta_data, colWidths=[1.5*inch, 5*inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))

        # Overall Summary
        story.append(Paragraph('OVERALL SUMMARY', heading_style))
        story.append(Spacer(1, 0.1*inch))

        summary_data = [
            ['Active Students:', str(len(student_stats))],
            ['Total Attempts:', str(total_attempts)],
            ['Correct Answers:', str(correct_attempts)],
            ['Overall Accuracy:', f'{accuracy:.1f}%'],
            ['Unique Questions:', str(unique_questions)],
        ]
        summary_table = Table(summary_data, colWidths=[2*inch, 4.5*inch])
        summary_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f4f8')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))

        # Topics Worked On
        if topics_data:
            story.append(Paragraph('TOPICS WORKED ON', heading_style))
            story.append(Spacer(1, 0.1*inch))

            topic_table_data = [['Topic', 'Attempts', 'Correct', 'Avg Score']]
            for topic in topics_data:
                topic_name = topic['question__topic__name'] or 'Uncategorized'
                topic_table_data.append([
                    topic_name,
                    str(topic['attempt_count']),
                    str(topic['correct_count']),
                    f"{topic['avg_score']:.1f}%"
                ])

            topic_table = Table(topic_table_data, colWidths=[3*inch, 1.2*inch, 1.2*inch, 1.1*inch])
            topic_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')]),
            ]))
            story.append(topic_table)
            story.append(Spacer(1, 0.3*inch))

        # Student Breakdown
        if student_stats:
            story.append(Paragraph('STUDENT BREAKDOWN', heading_style))
            story.append(Spacer(1, 0.1*inch))

            for i, student in enumerate(student_stats):
                if i > 0:
                    story.append(Spacer(1, 0.15*inch))

                story.append(Paragraph(f"{student['full_name']} ({student['username']})", styles['Heading3']))

                student_data = [
                    ['Attempts:', str(student['attempt_count'])],
                    ['Correct:', f"{student['correct_count']} ({student['accuracy']:.1f}%)"],
                    ['Average Score:', f"{student['avg_score']:.1f}%"],
                    ['Total Score (cumulative):', str(student['total_score'])],
                    ['Lessons Completed:', str(student['lessons_completed'])],
                ]

                student_table = Table(student_data, colWidths=[2*inch, 4*inch])
                student_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f9f9f9')),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ]))
                story.append(student_table)

                if student['topics']:
                    story.append(Spacer(1, 0.1*inch))
                    story.append(Paragraph('Topics:', styles['Normal']))
                    topic_items = []
                    for topic in student['topics'][:5]:
                        topic_name = topic['question__topic__name'] or 'Uncategorized'
                        topic_items.append([f"• {topic_name}:", f"{topic['count']} attempts"])

                    topic_items_table = Table(topic_items, colWidths=[3*inch, 1.5*inch])
                    topic_items_table.setStyle(TableStyle([
                        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                        ('FONTSIZE', (0, 0), (-1, -1), 8),
                        ('LEFTPADDING', (0, 0), (-1, -1), 15),
                    ]))
                    story.append(topic_items_table)
        else:
            story.append(Paragraph('No student activity in this period.', styles['Normal']))

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        # Return as downloadable PDF
        response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        filename = f'student_report_{days}day_{end_date.strftime("%Y%m%d")}.pdf'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

    def generate_daily_report(self, request, queryset):
        """Generate a report for the last 24 hours"""
        return self._generate_report(request, queryset, days=1)
    generate_daily_report.short_description = "📊 Generate Daily Report (24 hours)"

    def generate_weekly_report(self, request, queryset):
        """Generate a report for the last 7 days"""
        return self._generate_report(request, queryset, days=7)
    generate_weekly_report.short_description = "📊 Generate Weekly Report (7 days)"

    def generate_monthly_report(self, request, queryset):
        """Generate a report for the last 30 days"""
        return self._generate_report(request, queryset, days=30)
    generate_monthly_report.short_description = "📊 Generate Monthly Report (30 days)"

    def generate_yearly_report(self, request, queryset):
        """Generate a report for the last 365 days"""
        return self._generate_report(request, queryset, days=365)
    generate_yearly_report.short_description = "📊 Generate Yearly Report (365 days)"

    def generate_all_attempts_report(self, request, queryset):
        """Generate a PDF report of all question attempts by student and by topic"""
        # Get all students (exclude admin if needed)
        students_to_report = queryset if queryset.exists() else StudentProfile.objects.exclude(user=request.user)

        # Get all attempts for these students
        all_attempts = QuestionAttempt.objects.filter(student__in=students_to_report)

        # Part 1: Overall attempts per student (sorted by attempt count)
        student_data = []
        for student in students_to_report:
            attempt_count = all_attempts.filter(student=student).count()
            if attempt_count > 0:
                student_data.append({
                    'username': student.user.username,
                    'full_name': student.user.get_full_name() or student.user.username,
                    'total_attempts': attempt_count,
                })

        # Sort by total attempts (descending)
        student_data.sort(key=lambda x: x['total_attempts'], reverse=True)

        # Part 2: Attempts by topic for each student
        topic_breakdown = []
        for student in students_to_report:
            student_attempts = all_attempts.filter(student=student)
            if student_attempts.count() > 0:
                # Get topic-wise breakdown
                topics = student_attempts.values(
                    'question__topic__name'
                ).annotate(
                    attempt_count=Count('id')
                ).order_by('question__topic__name')

                if topics:
                    topic_breakdown.append({
                        'username': student.user.username,
                        'full_name': student.user.get_full_name() or student.user.username,
                        'topics': list(topics),
                    })

        # Generate PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=16, textColor=colors.HexColor('#1f4788'), alignment=TA_CENTER)
        heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#1f4788'))

        # Title
        story.append(Paragraph('STUDENT QUESTION ATTEMPTS REPORT - ALL TIME', title_style))
        story.append(Spacer(1, 0.2*inch))

        # Metadata
        meta_data = [
            ['Generated by:', request.user.username],
            ['Generated at:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')],
        ]
        if queryset.exists():
            meta_data.append(['Filtered to:', f'{queryset.count()} selected student(s)'])

        meta_table = Table(meta_data, colWidths=[1.5*inch, 5*inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))

        # Part 1: Overall attempts list
        story.append(Paragraph('PART 1: TOTAL QUESTION ATTEMPTS BY STUDENT', heading_style))
        story.append(Spacer(1, 0.1*inch))

        if student_data:
            part1_data = [['Student', 'Username', 'Total Attempts']]
            for student in student_data:
                part1_data.append([
                    student['full_name'],
                    student['username'],
                    str(student['total_attempts'])
                ])

            part1_table = Table(part1_data, colWidths=[2.5*inch, 2*inch, 2*inch])
            part1_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (2, 0), (2, -1), 'CENTER'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')]),
            ]))
            story.append(part1_table)
            story.append(Spacer(1, 0.2*inch))

            # Summary
            summary_text = f"Total Students: {len(student_data)} | Total Attempts (All Students): {sum(s['total_attempts'] for s in student_data)}"
            story.append(Paragraph(summary_text, styles['Normal']))
        else:
            story.append(Paragraph('No student attempts found.', styles['Normal']))

        story.append(Spacer(1, 0.4*inch))

        # Part 2: Topic breakdown
        story.append(Paragraph('PART 2: QUESTION ATTEMPTS BY TOPIC (PER STUDENT)', heading_style))
        story.append(Spacer(1, 0.2*inch))

        if topic_breakdown:
            for i, student in enumerate(topic_breakdown):
                if i > 0:
                    story.append(PageBreak())

                story.append(Paragraph(f"{student['full_name']} ({student['username']})", styles['Heading3']))
                story.append(Spacer(1, 0.1*inch))

                topic_data = [['Topic', 'Attempts']]
                total_student_attempts = 0
                for topic in student['topics']:
                    topic_name = topic['question__topic__name'] or 'Uncategorized'
                    attempt_count = topic['attempt_count']
                    total_student_attempts += attempt_count
                    topic_data.append([topic_name, str(attempt_count)])

                # Add total row
                topic_data.append(['TOTAL', str(total_student_attempts)])

                topic_table = Table(topic_data, colWidths=[4.5*inch, 2*inch])
                topic_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
                    ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
                    ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f0f0f0')]),
                ]))
                story.append(topic_table)
                story.append(Spacer(1, 0.2*inch))
        else:
            story.append(Paragraph('No topic data available.', styles['Normal']))

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        # Return as downloadable PDF
        response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        filename = f'student_attempts_all_time_{timezone.now().strftime("%Y%m%d_%H%M%S")}.pdf'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response
    generate_all_attempts_report.short_description = "📋 Generate All-Time Attempts Report (By Student & Topic)"

    def generate_weekly_attempts_report(self, request, queryset):
        """Generate a PDF report of question attempts over the last 7 days by student and topic"""
        # Get all students (exclude admin if needed)
        students_to_report = queryset if queryset.exists() else StudentProfile.objects.exclude(user=request.user)

        # Calculate 7 days ago
        seven_days_ago = timezone.now() - timedelta(days=7)

        # Get attempts from last 7 days for these students
        recent_attempts = QuestionAttempt.objects.filter(
            student__in=students_to_report,
            attempted_at__gte=seven_days_ago
        )

        # Part 1: Overall attempts per student (sorted by attempt count)
        student_data = []
        for student in students_to_report:
            attempt_count = recent_attempts.filter(student=student).count()
            if attempt_count > 0:
                student_data.append({
                    'username': student.user.username,
                    'full_name': student.user.get_full_name() or student.user.username,
                    'total_attempts': attempt_count,
                })

        # Sort by total attempts (descending)
        student_data.sort(key=lambda x: x['total_attempts'], reverse=True)

        # Part 2: Attempts by topic for each student
        topic_breakdown = []
        for student in students_to_report:
            student_attempts = recent_attempts.filter(student=student)
            if student_attempts.count() > 0:
                # Get topic-wise breakdown
                topics = student_attempts.values(
                    'question__topic__name'
                ).annotate(
                    attempt_count=Count('id')
                ).order_by('question__topic__name')

                if topics:
                    topic_breakdown.append({
                        'username': student.user.username,
                        'full_name': student.user.get_full_name() or student.user.username,
                        'topics': list(topics),
                    })

        # Sort topic_breakdown by total attempts (descending)
        topic_breakdown.sort(key=lambda x: sum(t['attempt_count'] for t in x['topics']), reverse=True)

        # Generate PDF
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=16, textColor=colors.HexColor('#1f4788'), alignment=TA_CENTER)
        heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=12, textColor=colors.HexColor('#1f4788'))

        # Title
        story.append(Paragraph('STUDENT QUESTION ATTEMPTS REPORT - LAST 7 DAYS', title_style))
        story.append(Spacer(1, 0.2*inch))

        # Metadata
        meta_data = [
            ['Period:', f"{seven_days_ago.strftime('%Y-%m-%d %H:%M')} to {timezone.now().strftime('%Y-%m-%d %H:%M')}"],
            ['Generated by:', request.user.username],
            ['Generated at:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')],
        ]
        if queryset.exists():
            meta_data.append(['Filtered to:', f'{queryset.count()} selected student(s)'])

        meta_table = Table(meta_data, colWidths=[1.5*inch, 5*inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.grey),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))

        # Part 1: Overall attempts list (sorted by attempts)
        story.append(Paragraph('PART 1: TOTAL QUESTION ATTEMPTS BY STUDENT (LAST 7 DAYS)', heading_style))
        story.append(Spacer(1, 0.1*inch))

        if student_data:
            part1_data = [['Student', 'Username', 'Total Attempts']]
            for student in student_data:
                part1_data.append([
                    student['full_name'],
                    student['username'],
                    str(student['total_attempts'])
                ])

            part1_table = Table(part1_data, colWidths=[2.5*inch, 2*inch, 2*inch])
            part1_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (2, 0), (2, -1), 'CENTER'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f0f0')]),
            ]))
            story.append(part1_table)
            story.append(Spacer(1, 0.2*inch))

            # Summary
            summary_text = f"Active Students (last 7 days): {len(student_data)} | Total Attempts: {sum(s['total_attempts'] for s in student_data)}"
            story.append(Paragraph(summary_text, styles['Normal']))
        else:
            story.append(Paragraph('No student attempts found in the last 7 days.', styles['Normal']))

        story.append(Spacer(1, 0.4*inch))

        # Part 2: Topic breakdown
        story.append(Paragraph('PART 2: QUESTION ATTEMPTS BY TOPIC (PER STUDENT)', heading_style))
        story.append(Spacer(1, 0.2*inch))

        if topic_breakdown:
            for i, student in enumerate(topic_breakdown):
                if i > 0:
                    story.append(PageBreak())

                story.append(Paragraph(f"{student['full_name']} ({student['username']})", styles['Heading3']))
                story.append(Spacer(1, 0.1*inch))

                topic_data = [['Topic', 'Attempts']]
                total_student_attempts = 0
                for topic in student['topics']:
                    topic_name = topic['question__topic__name'] or 'Uncategorized'
                    attempt_count = topic['attempt_count']
                    total_student_attempts += attempt_count
                    topic_data.append([topic_name, str(attempt_count)])

                # Add total row
                topic_data.append(['TOTAL', str(total_student_attempts)])

                topic_table = Table(topic_data, colWidths=[4.5*inch, 2*inch])
                topic_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTNAME', (0, 1), (-1, -2), 'Helvetica'),
                    ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f4788')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8f4f8')),
                    ('ALIGN', (1, 0), (1, -1), 'CENTER'),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f0f0f0')]),
                ]))
                story.append(topic_table)
                story.append(Spacer(1, 0.2*inch))
        else:
            story.append(Paragraph('No topic data available.', styles['Normal']))

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        # Return as downloadable PDF
        response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        filename = f'student_attempts_7days_{timezone.now().strftime("%Y%m%d_%H%M%S")}.pdf'
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response
    generate_weekly_attempts_report.short_description = "📅 Generate 7-Day Attempts Report (By Student & Topic)"


@admin.register(QuestionAttempt)
class QuestionAttemptAdmin(admin.ModelAdmin):
    list_display = ('student', 'question', 'question_part', 'score_awarded', 'is_correct', 'attempted_at')
    list_filter = ('is_correct', 'attempted_at')
    search_fields = ('student__user__username', 'question__id')
    readonly_fields = ('attempted_at', 'marks_awarded')


@admin.register(RegistrationCode)
class RegistrationCodeAdmin(admin.ModelAdmin):
    list_display = ('code', 'code_type', 'school', 'teacher_class', 'is_active', 'times_used', 'max_uses', 'description', 'created_at')
    list_filter = ('is_active', 'code_type', 'school', 'created_at')
    search_fields = ('code', 'description', 'school__name')
    readonly_fields = ('times_used', 'created_at')

    fieldsets = (
        ('Code Information', {
            'fields': ('code', 'code_type', 'school', 'description')
        }),
        ('Student Settings', {
            'fields': ('teacher_class',),
            'description': 'Only applicable for student codes. Links code to a specific class for auto-enrollment.'
        }),
        ('Usage Settings', {
            'fields': ('is_active', 'max_uses', 'times_used')
        }),
        ('Metadata', {
            'fields': ('created_at', 'created_by')
        }),
    )

    actions = ['deactivate_codes', 'activate_codes', 'generate_student_codes', 'generate_teacher_code']

    def deactivate_codes(self, request, queryset):
        queryset.update(is_active=False)
        self.message_user(request, f"{queryset.count()} code(s) deactivated.")
    deactivate_codes.short_description = "Deactivate selected codes"

    def activate_codes(self, request, queryset):
        queryset.update(is_active=True)
        self.message_user(request, f"{queryset.count()} code(s) activated.")
    activate_codes.short_description = "Activate selected codes"

    def generate_student_codes(self, request, queryset):
        """Generate 5 student registration codes"""
        codes_created = []
        for i in range(5):
            code = RegistrationCode.generate_code(length=8, prefix='STU-')
            reg_code = RegistrationCode.objects.create(
                code=code,
                code_type='student',
                max_uses=1,
                created_by=request.user,
                description=f'Student code generated by {request.user.username}'
            )
            codes_created.append(code)

        self.message_user(request, f"Generated 5 student codes: {', '.join(codes_created)}")
    generate_student_codes.short_description = "Generate 5 Student Codes"

    def generate_teacher_code(self, request, queryset):
        """Generate 1 teacher registration code"""
        code = RegistrationCode.generate_code(length=10, prefix='TCH-')
        reg_code = RegistrationCode.objects.create(
            code=code,
            code_type='teacher',
            max_uses=1,
            created_by=request.user,
            description=f'Teacher code generated by {request.user.username}'
        )

        self.message_user(request, f"Generated teacher code: {code}")
    generate_teacher_code.short_description = "Generate 1 Teacher Code"


@admin.register(LoginHistory)
class LoginHistoryAdmin(admin.ModelAdmin):
    list_display = ('status_icon', 'username_attempted', 'user_link', 'timestamp', 'ip_address', 'short_user_agent')
    list_filter = ('success', 'timestamp')
    search_fields = ('username_attempted', 'user__username', 'ip_address')
    readonly_fields = ('user', 'username_attempted', 'timestamp', 'success', 'ip_address', 'user_agent', 'session_key')
    date_hierarchy = 'timestamp'

    def has_add_permission(self, request):
        # Prevent manual creation - should only be created by signals
        return False

    def has_change_permission(self, request, obj=None):
        # Make records read-only
        return False

    def status_icon(self, obj):
        if obj.success:
            return format_html('<span style="color: green; font-size: 16px;">✓</span>')
        return format_html('<span style="color: red; font-size: 16px;">✗</span>')
    status_icon.short_description = 'Status'

    def user_link(self, obj):
        if obj.user:
            return format_html('<a href="/admin/auth/user/{}/change/">{}</a>', obj.user.id, obj.user.username)
        return '-'
    user_link.short_description = 'User'

    def short_user_agent(self, obj):
        if len(obj.user_agent) > 50:
            return obj.user_agent[:50] + '...'
        return obj.user_agent
    short_user_agent.short_description = 'Browser/Device'


@admin.register(UserSession)
class UserSessionAdmin(admin.ModelAdmin):
    list_display = ('user_link', 'login_time', 'last_activity', 'time_active', 'ip_address', 'short_user_agent', 'is_active_display')
    list_filter = ('login_time', 'last_activity')
    search_fields = ('user__username', 'ip_address')
    readonly_fields = ('user', 'session_key', 'ip_address', 'user_agent', 'login_time', 'last_activity')
    date_hierarchy = 'login_time'

    def has_add_permission(self, request):
        # Prevent manual creation - should only be created by signals
        return False

    def has_change_permission(self, request, obj=None):
        # Make records read-only
        return False

    def user_link(self, obj):
        return format_html('<a href="/admin/auth/user/{}/change/">{}</a>', obj.user.id, obj.user.username)
    user_link.short_description = 'User'

    def time_active(self, obj):
        duration = timezone.now() - obj.login_time
        hours = duration.total_seconds() // 3600
        minutes = (duration.total_seconds() % 3600) // 60
        if hours > 0:
            return f"{int(hours)}h {int(minutes)}m"
        return f"{int(minutes)}m"
    time_active.short_description = 'Duration'

    def is_active_display(self, obj):
        if obj.is_active():
            return format_html('<span style="color: green;">●</span> Active')
        return format_html('<span style="color: gray;">○</span> Expired')
    is_active_display.short_description = 'Status'

    def short_user_agent(self, obj):
        if len(obj.user_agent) > 50:
            return obj.user_agent[:50] + '...'
        return obj.user_agent
    short_user_agent.short_description = 'Browser/Device'

    actions = ['terminate_sessions']

    def terminate_sessions(self, request, queryset):
        from django.contrib.sessions.models import Session
        count = 0
        for user_session in queryset:
            try:
                session = Session.objects.get(session_key=user_session.session_key)
                session.delete()
                count += 1
            except Session.DoesNotExist:
                pass
        self.message_user(request, f"{count} session(s) terminated.")
    terminate_sessions.short_description = "Terminate selected sessions"
