# Generated by Django 5.2.7 on 2025-11-23 08:56

import django.db.models.deletion
import django.utils.timezone
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for the news item', max_length=200)),
                ('content', markdownx.models.MarkdownxField(help_text='Content with markdown and LaTeX support')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this item becomes visible')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional: when this item should no longer display', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned items appear at the top')),
                ('is_dismissible', models.BooleanField(default=True, help_text='If False, students cannot dismiss this item (use for critical announcements)')),
                ('category', models.CharField(choices=[('general', 'General'), ('new_content', 'New Content'), ('tips', 'Study Tips'), ('system', 'System Update'), ('event', 'Event')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ManyToManyField(blank=True, help_text='Students who have dismissed this item', related_name='dismissed_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
    ]
