# Generated by Django 5.2.7 on 2026-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('homework', '0002_homeworknotificationsnooze'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for general announcement to all students. Select classes for targeted announcements.', related_name='news_items', to='homework.teacherclass'),
        ),
    ]
