# Generated by Django 5.2.7 on 2025-12-07 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_papers', '0007_merge_20251205_1131'),
        ('interactive_lessons', '0017_link_questions_to_sections'),
        ('quickkicks', '0003_rename_geogebra_url_to_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Assignment title (e.g., 'Trigonometry Week 1')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or notes for students')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this homework was assigned')),
                ('due_date', models.DateTimeField(help_text='When this homework is due')),
                ('is_published', models.BooleanField(default=False, help_text='Whether students can see this assignment (draft mode if False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_students', models.ManyToManyField(blank=True, help_text='Individual students assigned this homework (in addition to classes)', limit_choices_to={'is_staff': False}, related_name='individual_assignments', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(help_text='Topic this homework covers', on_delete=django.db.models.deletion.PROTECT, related_name='homework_assignments', to='interactive_lessons.topic')),
            ],
            options={
                'verbose_name': 'Homework Assignment',
                'verbose_name_plural': 'Homework Assignments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('quickkick', 'QuickKick Video/Applet')], help_text='Type of content for this task', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Specific instructions for this task')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this task is mandatory or optional')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(help_text='Homework assignment this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='homework.homeworkassignment')),
                ('exam_question', models.ForeignKey(blank=True, help_text="Exam question to practice (if task_type='exam_question')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='exam_papers.examquestion')),
                ('quickkick', models.ForeignKey(blank=True, help_text="QuickKick to watch (if task_type='quickkick')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='quickkicks.quickkick')),
                ('section', models.ForeignKey(blank=True, help_text="Section to complete (if task_type='section')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='interactive_lessons.section')),
            ],
            options={
                'verbose_name': 'Homework Task',
                'verbose_name_plural': 'Homework Tasks',
                'ordering': ['assignment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Class name (e.g., '6th Year Maths A', 'Leaving Cert Group 1')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Students enrolled in this class', limit_choices_to={'is_staff': False}, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['teacher', 'name'],
            },
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes assigned this homework', related_name='assignments', to='homework.teacherclass'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Display name (e.g., 'Mr. Smith', 'Ms. O'Brien')", max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Can create homework assignments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Must be a staff user', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who manages this class', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='homework.teacherprofile'),
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who created this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='homework.teacherprofile'),
        ),
        migrations.CreateModel(
            name='StudentHomeworkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Student's notes or reflections on this task")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='homework.homeworkassignment')),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_progress', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='homework.homeworktask')),
            ],
            options={
                'verbose_name': 'Student Homework Progress',
                'verbose_name_plural': 'Student Homework Progress',
                'ordering': ['assignment', 'task__order'],
                'unique_together': {('student', 'assignment', 'task')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False, help_text='Whether this was submitted after the due date')),
                ('teacher_comment', models.TextField(blank=True, help_text="Teacher's feedback on the submission")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='homework.teacherprofile')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
