# Generated by Django 5.2.7 on 2025-12-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkNotificationSnooze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoozed_until', models.DateTimeField(help_text="Notification won't show until after this time")),
                ('student', models.OneToOneField(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_snooze', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework Notification Snooze',
                'verbose_name_plural': 'Homework Notification Snoozes',
            },
        ),
    ]
