# Generated by Django 5.2.7 on 2026-01-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homeworknotificationsnooze'),
        ('schools', '0003_school_is_gaelscoil_school_secondary_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this teacher belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Individual students assigned this homework (in addition to classes)', related_name='individual_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeworknotificationsnooze',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_snooze', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenthomeworkprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students enrolled in this class', related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
