# Generated by Django 5.2.7 on 2026-01-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        ('homework', '0003_teacherprofile_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='flashcard_set',
            field=models.ForeignKey(blank=True, help_text="Flashcard set to study (if task_type='flashcard')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='flashcards.flashcardset'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='task_type',
            field=models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('quickkick', 'QuickKick Video/Applet'), ('flashcard', 'Flashcard Set')], help_text='Type of content for this task', max_length=20),
        ),
    ]
