# Generated by Django 5.2.7 on 2026-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_homeworktask_flashcard_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktask',
            name='task_type',
            field=models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('quickkick', 'QuickFlicks Video/Applet'), ('flashcard', 'Flashcard Set')], help_text='Type of content for this task', max_length=20),
        ),
    ]
