# Generated by Django 5.2.7 on 2026-01-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_homeworktask_task_type'),
        ('quickkicks', '0007_alter_quickkick_options_alter_quickkickview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktask',
            name='quickkick',
            field=models.ForeignKey(blank=True, help_text="QuickFlicks to watch (if task_type='quickkick')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='quickkicks.quickkick', verbose_name='QuickFlicks'),
        ),
    ]
