# Generated by Django 5.2.7 on 2026-01-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_change_teacherprofile_to_protect'),
        ('interactive_lessons', '0029_questionpart_solution_unlock_after_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic to filter content by (Select this first to filter other options)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homework_tasks_direct', to='interactive_lessons.topic'),
        ),
    ]
