# Generated by Django 5.2.7 on 2026-01-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_homeworktask_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworktask',
            name='topic',
        ),
    ]
