# Generated by Django 5.2.7 on 2026-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_remove_homeworktask_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether email notifications have been sent for this assignment'),
        ),
    ]
