# Generated by Django 5.2.7 on 2026-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_add_notification_sent_to_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktask',
            name='task_type',
            field=models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('quickkick', 'QuickFlicks Video/Applet'), ('flashcard', 'Flashcard Set'), ('custom', 'Written Exercise')], help_text='Type of content for this task', max_length=20),
        ),
    ]
