# Generated by Django 5.2.17 on 2026-09-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0021_examquestionpart_topics'),
        ('homework', '0011_alter_homeworktask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktask',
            name='exam_question_part',
            field=models.ForeignKey(blank=True, help_text="Single exam question part to practice (if task_type='exam_part')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='exam_papers.examquestionpart'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='task_type',
            field=models.CharField(choices=[('section', 'Topic Section'), ('exam_question', 'Exam Question'), ('exam_part', 'Exam Question Part'), ('quickkick', 'QuickFlicks Video/Applet'), ('flashcard', 'Flashcard Set'), ('custom', 'Written Exercise')], help_text='Type of content for this task', max_length=20),
        ),
    ]
