# Generated by Django 5.2.7 on 2025-12-27 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactive_lessons", "0018_question_is_copyrighted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title (e.g., 'Trigonometry Identities', 'Differentiation Rules')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief overview of what this set covers"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within topic"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Make visible to students (draft mode if False)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flashcard_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic this flashcard set belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to="interactive_lessons.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard Set",
                "verbose_name_plural": "Flashcard Sets",
                "ordering": ("topic", "order", "title"),
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "front_text",
                    models.TextField(
                        help_text="Front content - supports Markdown and LaTeX (use $...$ for inline, $$...$$ for display)"
                    ),
                ),
                (
                    "front_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for front of card",
                        null=True,
                        upload_to="flashcards/front/",
                    ),
                ),
                (
                    "back_text",
                    models.TextField(
                        help_text="Correct answer text - supports Markdown and LaTeX"
                    ),
                ),
                (
                    "back_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for back of card (e.g., diagram, worked solution)",
                        null=True,
                        upload_to="flashcards/back/",
                    ),
                ),
                (
                    "distractor_1",
                    models.TextField(
                        help_text="First incorrect option - supports Markdown and LaTeX"
                    ),
                ),
                (
                    "distractor_2",
                    models.TextField(
                        help_text="Second incorrect option - supports Markdown and LaTeX"
                    ),
                ),
                (
                    "distractor_3",
                    models.TextField(
                        help_text="Third incorrect option - supports Markdown and LaTeX"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation shown after answering (why answer is correct)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within set"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        help_text="Set this card belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="flashcards.flashcardset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
                "ordering": ("flashcard_set", "order"),
            },
        ),
        migrations.CreateModel(
            name="FlashcardAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times student has viewed this card",
                    ),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times answered correctly"
                    ),
                ),
                (
                    "incorrect_count",
                    models.PositiveIntegerField(
                        default=0, help_text="How many times answered incorrectly"
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("new", "New (Never Seen)"),
                            ("learning", "Learning"),
                            ("know", "Know"),
                            ("dont_know", "Don't Know"),
                        ],
                        default="new",
                        help_text="Current mastery state for this card",
                        max_length=20,
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time student viewed this card"
                    ),
                ),
                (
                    "last_answered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time student answered this card",
                        null=True,
                    ),
                ),
                (
                    "last_answer_correct",
                    models.BooleanField(
                        blank=True, help_text="Was the last answer correct?", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard Attempt",
                "verbose_name_plural": "Flashcard Attempts",
                "ordering": ["-last_viewed_at"],
                "unique_together": {("student", "flashcard")},
            },
        ),
    ]
