# Generated by Django 5.2.7 on 2026-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardattempt",
            name="mastery_level",
            field=models.CharField(
                choices=[
                    ("new", "New (Never Seen)"),
                    ("learning", "Learning"),
                    ("know", "Know"),
                    ("dont_know", "Don't Know"),
                    ("retired", "Retired"),
                ],
                default="new",
                help_text="Current mastery state for this card",
                max_length=20,
            ),
        ),
    ]
