"""
Management command to seed initial school contact data.
Usage: python manage.py seed_schools
"""

from django.core.management.base import BaseCommand
from schools.models import School


class Command(BaseCommand):
    help = 'Seeds the database with initial school contact information'

    def handle(self, *args, **options):
        """Populate database with initial school data from research."""

        schools_data = [
            {
                'name': 'Newbridge College',
                'principal_name': 'Mr. Patrick O\'Brien',
                'email': 'info@newbridge-college.ie',
                'phone': '+353 45 487200',
                'address': 'Newbridge, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'secondary',
                'website': 'https://www.newbridgecollege.ie',
            },
            {
                'name': 'Blackrock College',
                'principal_name': 'Ms. Yvonne Markey',
                'email': 'info@blackrockcollege.com',
                'phone': '+353 1 275 2100',
                'address': 'Rock Road, Blackrock, Co. Dublin A94 FK84',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.blackrockcollege.com',
            },
            {
                'name': 'Castleknock College',
                'principal_name': 'Miss Elaine Kelly',
                'email': 'principalpa@castleknockcollege.ie',
                'phone': '',
                'address': 'Castleknock, Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.castleknockcollege.ie',
            },
            {
                'name': 'Coláiste Íosagáin',
                'principal_name': 'Treasa Ní Fhearraigh',
                'email': 'eolas@eoiniosagain.ie',
                'phone': '',
                'address': 'Stillorgan Road, Booterstown, Blackrock, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': '',
                'is_gaelscoil': True,
            },
            {
                'name': 'Christian Brothers College Cork',
                'principal_name': 'Mr. David Lordon',
                'email': 'enquire@cbccork.ie',
                'phone': '0214501653',
                'address': 'Sidney Hill, Wellington Road, Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.cbccork.ie',
            },
            {
                'name': 'Presentation Brothers College Cork',
                'principal_name': 'Mr. David Barry',
                'email': 'info@pbc-cork.ie',
                'phone': '021-4272743',
                'address': 'The Mardyke, Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.pbc-cork.ie',
            },
            {
                'name': 'Cork Educate Together Secondary School',
                'principal_name': 'Mr. Colm O\'Connor',
                'email': 'info@cetsl.ie',
                'phone': '',
                'address': 'Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'http://www.cetsl.ie',
            },
            {
                'name': 'St. Munchin\'s College',
                'principal_name': 'Mr. Shane Fitzgerald',
                'email': 'office@stmunchinscollege.ie',
                'phone': '061348922',
                'address': 'Corbally, Limerick',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'http://www.stmunchinscollege.com',
            },
            {
                'name': 'Ardscoil Rís Limerick',
                'principal_name': 'Mr. Tom Prendergast',
                'email': 'asroffice@eircom.net',
                'phone': '061-453828',
                'address': 'North Circular Road, Limerick V94 V602',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'https://www.ardscoil.com',
            },
            {
                'name': 'Coláiste Chiaráin Athlone',
                'principal_name': 'Mr. Brendan Waldron',
                'email': 'info@ccathlone.ie',
                'phone': '090 6492383',
                'address': 'Summerhill, Athlone, Co. Roscommon',
                'county': 'Roscommon',
                'school_type': 'secondary',
                'website': 'https://www.ccathlone.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'St Kieran\'s College Kilkenny',
                'principal_name': 'Mr. Adrian Finan',
                'email': 'school@stkieranscollege.ie',
                'phone': '0567761707',
                'address': 'College Road, Kilkenny',
                'county': 'Kilkenny',
                'school_type': 'secondary',
                'website': 'https://www.stkieranscollege.ie',
            },
            {
                'name': 'Galway City & Oranmore Educate Together Secondary School',
                'principal_name': 'Ms. Sarah Molloy',
                'email': 'admin@galwayetss.ie',
                'phone': '091 394262',
                'address': 'Newtownsmith, Galway City Centre, Galway',
                'county': 'Galway',
                'school_type': 'secondary',
                'website': 'https://galwayetss.ie',
            },
            {
                'name': 'Loreto College St Stephen\'s Green',
                'principal_name': 'Ms. Jacqueline Dempsey',
                'email': 'info@loretothegreen.ie',
                'phone': '016618179',
                'address': '53 St Stephens Green Dublin 2',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretothegreen.ie',
            },
            {
                'name': 'Gonzaga College',
                'principal_name': 'Mr. Damon McCaul',
                'email': 'headmaster@gonzaga.ie',
                'phone': '014972931',
                'address': 'Sandford Road, Ranelagh, Dublin 6',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': '',
            },
            {
                'name': 'Coláiste Eoin Finglas',
                'principal_name': 'Neil Dunphy',
                'email': 'info@eoin.cdetb.ie',
                'phone': '018341426',
                'address': 'Cappagh Road, Finglas West, Dublin 11',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://colaisteeoin.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'St Andrew\'s College Dublin',
                'principal_name': 'Ms Louise Marshall',
                'email': 'information@st-andrews.ie',
                'phone': '',
                'address': 'Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.sac.ie',
            },
            {
                'name': 'Mercy Mounthawk Secondary School',
                'principal_name': 'Mr. Patrick Fleming',
                'email': 'admin@mercymounthawk.ie',
                'phone': '066 710 2550',
                'address': 'Mounthawk, Tralee, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'secondary',
                'website': 'https://mercymounthawk.ie',
            },
            {
                'name': 'Loreto Abbey Secondary School Dalkey',
                'principal_name': 'Mr. Robert Dunne',
                'email': 'principal@loretoabbeydalkey.ie',
                'phone': '012718900',
                'address': 'Loreto Avenue, Off Harbour Road, Dalkey, Co. Dublin A96 YC81',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretoabbeydalkey.com',
            },
            {
                'name': 'Coláiste Pobail Acla',
                'principal_name': 'Jason Ó Mongáin',
                'email': '[email protected]',
                'phone': '098 45139',
                'address': 'Polranny, Achill, Co. Mayo',
                'county': 'Mayo',
                'school_type': 'community',
                'website': 'https://colaistepobailacla.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Presentation Secondary School Waterford',
                'principal_name': 'Ms. Sally Ronayne',
                'email': 'principal@preswaterford.ie',
                'phone': '051376584',
                'address': 'Cannon Street, Waterford',
                'county': 'Waterford',
                'school_type': 'secondary',
                'website': 'https://www.presentationsecondarywaterford.ie',
            },
            {
                'name': 'Stanhope Secondary School',
                'principal_name': 'Mr. John O\'Brien',
                'email': 'info@stanhopesecondary.ie',
                'phone': '01-6710419',
                'address': 'Manor Street, Stoneybatter, Dublin 7, D07 YP03',
                'county': 'Dublin',
                'school_type': 'secondary',
                'roll_number': '60843Q',
                'website': 'https://stanhopesecondary.ie',
                'is_gaelscoil': False,
                'secondary_contact_name': 'S. Mulligan',
                'secondary_contact_role': 'Contact',
                'secondary_contact_email': 'smulligan@stanhopesecondary.ie',
            },
            # Additional 50 schools for outreach campaign
            {
                'name': 'Rockwell College',
                'principal_name': 'Mr. Dónal Ó Ceallaigh',
                'email': 'info@rockwellcollege.ie',
                'phone': '062 61444',
                'address': 'Cashel, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.rockwellcollege.ie',
            },
            {
                'name': 'Clongowes Wood College',
                'principal_name': 'Mr. Chris Lumb',
                'email': 'reception@clongowes.net',
                'phone': '045 868202',
                'address': 'Clane, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'secondary',
                'website': 'https://www.clongowes.net',
            },
            {
                'name': 'Belvedere College',
                'principal_name': 'Mr. Paul Meany',
                'email': 'info@belvedere.ie',
                'phone': '01 858 5800',
                'address': 'Great Denmark Street, Dublin 1',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.belvedere.ie',
            },
            {
                'name': 'St Michael\'s College',
                'principal_name': 'Mr. Paul Gilligan',
                'email': 'office@stmichaelscollege.ie',
                'phone': '01 269 1003',
                'address': 'Ailesbury Road, Dublin 4',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stmichaelscollege.ie',
            },
            {
                'name': 'Terenure College',
                'principal_name': 'Mr. Thomas Geraghty',
                'email': 'secretary@terenure.ie',
                'phone': '01 490 7507',
                'address': 'Templeogue Road, Dublin 6W',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.terenure.ie',
            },
            {
                'name': 'Coláiste Iognáid',
                'principal_name': 'Caitríona Ní Chualáin',
                'email': 'admin@colaisteiognaid.ie',
                'phone': '091 529 900',
                'address': 'Sea Road, Galway',
                'county': 'Galway',
                'school_type': 'secondary',
                'website': 'https://www.colaisteiognaid.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Cistercian College Roscrea',
                'principal_name': 'Mr. Tomás Ó Murchú',
                'email': 'info@ccr.ie',
                'phone': '0505 25344',
                'address': 'Mount St Joseph, Roscrea, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.ccr.ie',
            },
            {
                'name': 'St Columba\'s College',
                'principal_name': 'Ms. Pauline Dooley',
                'email': 'schooloffice@stcolumbas.ie',
                'phone': '01 490 6791',
                'address': 'Whitechurch, Dublin 16',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stcolumbas.ie',
            },
            {
                'name': 'Sligo Grammar School',
                'principal_name': 'Mr. Brendan Finlay',
                'email': 'info@sligogrammar.ie',
                'phone': '071 916 1809',
                'address': 'The Mall, Sligo',
                'county': 'Sligo',
                'school_type': 'secondary',
                'website': 'https://www.sligogrammar.ie',
            },
            {
                'name': 'Wesley College Dublin',
                'principal_name': 'Mr. Dermot Dunne',
                'email': 'info@wesleycollege.ie',
                'phone': '01 495 3900',
                'address': 'Ballinteer, Dublin 16',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.wesleycollege.ie',
            },
            {
                'name': 'Synge Street CBS',
                'principal_name': 'Mr. Brendan Farrell',
                'email': 'info@syngestreet.ie',
                'phone': '01 453 3737',
                'address': 'Synge Street, Dublin 8',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.syngestreet.ie',
            },
            {
                'name': 'Muckross Park College',
                'principal_name': 'Ms. Alison O\'Mahony',
                'email': 'info@muckrosspark.ie',
                'phone': '01 269 8844',
                'address': 'Marlborough Road, Donnybrook, Dublin 4',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.muckrosspark.ie',
            },
            {
                'name': 'Loreto College Foxrock',
                'principal_name': 'Ms. Ann Marie Mullen',
                'email': 'info@loretofoxrock.ie',
                'phone': '01 289 3042',
                'address': 'Foxrock, Dublin 18',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretofoxrock.ie',
            },
            {
                'name': 'Mount Anville Secondary School',
                'principal_name': 'Ms. Finola Kennedy',
                'email': 'office@mountanville.ie',
                'phone': '01 288 9364',
                'address': 'Mount Anville Road, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.mountanville.ie',
            },
            {
                'name': 'St Gerard\'s School Bray',
                'principal_name': 'Ms. Michelle McNiffe',
                'email': 'info@stgerardsbray.ie',
                'phone': '01 286 8991',
                'address': 'Bray, Co. Wicklow',
                'county': 'Wicklow',
                'school_type': 'secondary',
                'website': 'https://www.stgerardsbray.ie',
            },
            {
                'name': 'De La Salle College Waterford',
                'principal_name': 'Mr. John Gallagher',
                'email': 'info@delasallewaterford.com',
                'phone': '051 874385',
                'address': 'Newtown, Waterford',
                'county': 'Waterford',
                'school_type': 'secondary',
                'website': 'https://www.delasallewaterford.com',
            },
            {
                'name': 'Villiers School Limerick',
                'principal_name': 'Ms. Jill Storey',
                'email': 'office@villiers-school.com',
                'phone': '061 451447',
                'address': 'North Circular Road, Limerick',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'https://www.villiers-school.com',
            },
            {
                'name': 'Ursuline College Sligo',
                'principal_name': 'Ms. Attracta McKeon',
                'email': 'ursuline@eircom.net',
                'phone': '071 916 1790',
                'address': 'John Street, Sligo',
                'county': 'Sligo',
                'school_type': 'secondary',
                'website': 'https://www.ursulinecollege.ie',
            },
            {
                'name': 'Carrick-on-Suir CBS',
                'principal_name': 'Mr. David Nagle',
                'email': 'carrickonsuircbs@eircom.net',
                'phone': '051 640607',
                'address': 'Greenside, Carrick-on-Suir, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.carrickonsuircbs.com',
            },
            {
                'name': 'St Mary\'s College Dundalk',
                'principal_name': 'Mr. Noel Rodgers',
                'email': 'info@stmaryscollegedundalk.ie',
                'phone': '042 933 1670',
                'address': 'Dundalk, Co. Louth',
                'county': 'Louth',
                'school_type': 'secondary',
                'website': 'https://www.stmaryscollegedundalk.ie',
            },
            {
                'name': 'St Vincent\'s CBS Glasnevin',
                'principal_name': 'Mr. Frank Ruane',
                'email': 'office@vcbsglasnevin.ie',
                'phone': '01 837 9445',
                'address': 'St Vincent\'s Road, Glasnevin, Dublin 11',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.vcbsglasnevin.ie',
            },
            {
                'name': 'Ard Scoil na Mara Tramore',
                'principal_name': 'Ms. Siobhan Heffernan',
                'email': 'admin@asnamaratramore.ie',
                'phone': '051 381011',
                'address': 'Tramore, Co. Waterford',
                'county': 'Waterford',
                'school_type': 'community',
                'website': 'https://www.asnamaratramore.ie',
            },
            {
                'name': 'Moyle Park College',
                'principal_name': 'Ms. Linda Murphy',
                'email': 'office@moylepark.ie',
                'phone': '01 457 6565',
                'address': 'Clondalkin, Dublin 22',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.moylepark.ie',
            },
            {
                'name': 'Coláiste Mhuire Ennis',
                'principal_name': 'Mr. Fergal McDonagh',
                'email': 'cmcennis@eircom.net',
                'phone': '065 682 9710',
                'address': 'Harmony Row, Ennis, Co. Clare',
                'county': 'Clare',
                'school_type': 'secondary',
                'website': 'https://www.colaiste-mhuire.com',
            },
            {
                'name': 'St Flannan\'s College Ennis',
                'principal_name': 'Mr. John Hanly',
                'email': 'info@stflannans.ie',
                'phone': '065 682 8093',
                'address': 'Ennis, Co. Clare',
                'county': 'Clare',
                'school_type': 'secondary',
                'website': 'https://www.stflannans.ie',
            },
            {
                'name': 'Carlow Vocational School',
                'principal_name': 'Mr. Fergal O\'Neill',
                'email': 'admin@carlowvec.ie',
                'phone': '059 913 0977',
                'address': 'Kilkenny Road, Carlow',
                'county': 'Carlow',
                'school_type': 'vocational',
                'website': 'https://www.carlowvocationalschool.ie',
            },
            {
                'name': 'St Leo\'s College Carlow',
                'principal_name': 'Ms. Ann Marie Ahern',
                'email': 'office@stleoscarlow.ie',
                'phone': '059 914 2052',
                'address': 'Dublin Road, Carlow',
                'county': 'Carlow',
                'school_type': 'secondary',
                'website': 'https://www.stleoscarlow.ie',
            },
            {
                'name': 'Loreto College Cavan',
                'principal_name': 'Ms. Marie Hannon',
                'email': 'loretocavan@eircom.net',
                'phone': '049 433 1711',
                'address': 'Cavan',
                'county': 'Cavan',
                'school_type': 'secondary',
                'website': 'https://www.loretocavan.ie',
            },
            {
                'name': 'St Patrick\'s College Cavan',
                'principal_name': 'Mr. John Crowe',
                'email': 'info@stpatscavan.ie',
                'phone': '049 433 1044',
                'address': 'Cavan',
                'county': 'Cavan',
                'school_type': 'secondary',
                'website': 'https://www.stpatscavan.ie',
            },
            {
                'name': 'Pobalscoil Chorca Dhuibhne',
                'principal_name': 'Mairéad Uí Shé',
                'email': 'pobalscoil@eircom.net',
                'phone': '066 915 1034',
                'address': 'Dingle, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'community',
                'website': 'https://www.pobalscoildingle.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Midleton College',
                'principal_name': 'Mr. William Halpin',
                'email': 'office@midletoncollege.ie',
                'phone': '021 463 1737',
                'address': 'Midleton, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.midletoncollege.ie',
            },
            {
                'name': 'St Brogan\'s College Bandon',
                'principal_name': 'Mr. Eoin Deasy',
                'email': 'office@stbrogans.ie',
                'phone': '023 884 1913',
                'address': 'Bandon, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.stbrogans.ie',
            },
            {
                'name': 'St Mary\'s Secondary School Mallow',
                'principal_name': 'Ms. Frances O\'Leary',
                'email': 'office@smsmallow.ie',
                'phone': '022 21366',
                'address': 'Mallow, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.smsmallow.ie',
            },
            {
                'name': 'Ashbourne Community School',
                'principal_name': 'Mr. Seán O\'Sullivan',
                'email': 'info@ashbournecs.ie',
                'phone': '01 835 0611',
                'address': 'Ashbourne, Co. Meath',
                'county': 'Meath',
                'school_type': 'community',
                'website': 'https://www.ashbournecs.ie',
            },
            {
                'name': 'Eureka Secondary School Kells',
                'principal_name': 'Ms. Therese O\'Brien',
                'email': 'eurekakells@eircom.net',
                'phone': '046 924 0233',
                'address': 'Kells, Co. Meath',
                'county': 'Meath',
                'school_type': 'secondary',
                'website': 'https://www.eurekakells.ie',
            },
            {
                'name': 'Tullamore College',
                'principal_name': 'Mr. Michael Cahill',
                'email': 'info@tullamorecollege.ie',
                'phone': '057 935 2474',
                'address': 'Tullamore, Co. Offaly',
                'county': 'Offaly',
                'school_type': 'community',
                'website': 'https://www.tullamorecollege.ie',
            },
            {
                'name': 'Coláiste Choilm Ballincollig',
                'principal_name': 'Mr. William O\'Shea',
                'email': 'office@colaistechoilm.ie',
                'phone': '021 487 1447',
                'address': 'Ballincollig, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.colaistechoilm.ie',
            },
            {
                'name': 'Coláiste na Toirbhirte Bandon',
                'principal_name': 'Mr. William Morrissey',
                'email': 'office@toirbhirtebandon.ie',
                'phone': '023 884 1713',
                'address': 'Bandon, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.toirbhirtebandon.ie',
            },
            {
                'name': 'Hazelwood College Dromcollogher',
                'principal_name': 'Mr. Patrick O\'Connor',
                'email': 'hazelwoodcollege@eircom.net',
                'phone': '063 83102',
                'address': 'Dromcollogher, Co. Limerick',
                'county': 'Limerick',
                'school_type': 'community',
                'website': 'https://www.hazelwoodcollege.ie',
            },
            {
                'name': 'St Nessan\'s Community College Moate',
                'principal_name': 'Ms. Mairead Fox',
                'email': 'info@stnessans.ie',
                'phone': '090 648 1076',
                'address': 'Moate, Co. Westmeath',
                'county': 'Westmeath',
                'school_type': 'community',
                'website': 'https://www.stnessans.ie',
            },
            {
                'name': 'St Aidan\'s Comprehensive School Cootehill',
                'principal_name': 'Mr. Colm Ryan',
                'email': 'info@staidanscootehill.ie',
                'phone': '049 555 2142',
                'address': 'Cootehill, Co. Cavan',
                'county': 'Cavan',
                'school_type': 'comprehensive',
                'website': 'https://www.staidanscootehill.ie',
            },
            {
                'name': 'Coláiste Pobail Setanta',
                'principal_name': 'Seán Ó Lideadha',
                'email': 'setanta@cpsetanta.ie',
                'phone': '01 848 0433',
                'address': 'Pembroke Cottages, Dublin 4',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.cpsetanta.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Coláiste de hÍde Tallaght',
                'principal_name': 'Máire Uí Fhearraigh',
                'email': 'office@colaistdehide.ie',
                'phone': '01 451 5741',
                'address': 'Tallaght, Dublin 24',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.colaistdehide.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Ashfield College Dublin',
                'principal_name': 'Mr. David Boyd',
                'email': 'info@ashfield.ie',
                'phone': '01 475 5877',
                'address': 'Dundrum, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.ashfield.ie',
            },
            {
                'name': 'Coláiste Éanna Cabra',
                'principal_name': 'Caitríona Ní Cheallaigh',
                'email': 'info@colaisteeanna.ie',
                'phone': '01 838 3615',
                'address': 'Cabra, Dublin 7',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.colaisteeanna.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Holy Family Community School Newbridge',
                'principal_name': 'Mr. Tom O\'Reilly',
                'email': 'office@holyfamilynewbridge.ie',
                'phone': '045 431 931',
                'address': 'Newbridge, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'community',
                'website': 'https://www.holyfamilynewbridge.ie',
            },
            {
                'name': 'St Mary\'s Secondary School Macroom',
                'principal_name': 'Ms. Ann Hennessy',
                'email': 'admin@stmarymacroom.ie',
                'phone': '026 41130',
                'address': 'Macroom, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.stmarysmacroom.ie',
            },
            {
                'name': 'Ballymakenny College Drogheda',
                'principal_name': 'Mr. Derek Sheridan',
                'email': 'office@ballymakennycollege.ie',
                'phone': '041 983 8272',
                'address': 'Drogheda, Co. Louth',
                'county': 'Louth',
                'school_type': 'community',
                'website': 'https://www.ballymakennycollege.ie',
            },
            {
                'name': 'St Joseph\'s Secondary School Drogheda',
                'principal_name': 'Ms. Catherine King',
                'email': 'stjosephsrogheda@eircom.net',
                'phone': '041 983 8671',
                'address': 'Drogheda, Co. Louth',
                'county': 'Louth',
                'school_type': 'secondary',
                'website': 'https://www.stjosephsdrogheda.ie',
            },
            # Additional 50 schools - second batch
            {
                'name': 'Rathdown School',
                'principal_name': 'Ms. Fionnuala Waldron',
                'email': 'office@rathdownschool.ie',
                'phone': '01 493 2810',
                'address': 'Upper Glenageary Road, Glenageary, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.rathdownschool.ie',
            },
            {
                'name': 'Sutton Park School',
                'principal_name': 'Mr. Paul Barker',
                'email': 'info@suttonpark.ie',
                'phone': '01 832 2940',
                'address': 'St Fintan\'s Road, Sutton, Dublin 13',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.suttonpark.ie',
            },
            {
                'name': 'The High School Dublin',
                'principal_name': 'Mr. Alan Kelly',
                'email': 'admin@thehighschool.ie',
                'phone': '01 497 0506',
                'address': 'Zion Road, Rathgar, Dublin 6',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.thehighschool.ie',
            },
            {
                'name': 'Rockbrook Park School',
                'principal_name': 'Ms. Georgina Sweeney',
                'email': 'info@rockbrook.ie',
                'phone': '01 493 5666',
                'address': 'Rockbrook, Rathfarnham, Dublin 16',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.rockbrook.ie',
            },
            {
                'name': 'Sandford Park School',
                'principal_name': 'Mr. Bruce Ferguson',
                'email': 'info@sandfordpark.ie',
                'phone': '01 497 4857',
                'address': 'Ranelagh, Dublin 6',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.sandfordpark.ie',
            },
            {
                'name': 'St Kilian\'s German School',
                'principal_name': 'Mr. Thomas Holz',
                'email': 'info@kilians.com',
                'phone': '01 288 5680',
                'address': 'Roebuck Road, Clonskeagh, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.kilians.com',
            },
            {
                'name': 'St Conleth\'s College',
                'principal_name': 'Mr. Michael Keane',
                'email': 'info@stconleths.ie',
                'phone': '01 676 2013',
                'address': '28-32 Clyde Road, Ballsbridge, Dublin 4',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stconleths.ie',
            },
            {
                'name': 'Newpark Comprehensive School',
                'principal_name': 'Ms. Sarah O\'Reilly',
                'email': 'admin@newparkschool.ie',
                'phone': '01 298 2658',
                'address': 'Newtownpark Avenue, Blackrock, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'comprehensive',
                'website': 'https://www.newparkschool.ie',
            },
            {
                'name': 'Oatlands College',
                'principal_name': 'Mr. Michael O\'Grady',
                'email': 'info@oatlands.ie',
                'phone': '01 288 1471',
                'address': 'Mount Anville Road, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.oatlands.ie',
            },
            {
                'name': 'St Benildus College',
                'principal_name': 'Mr. Andrew Rafter',
                'email': 'info@benildus.ie',
                'phone': '01 490 8022',
                'address': 'Kilmacud Road, Stillorgan, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.benildus.ie',
            },
            {
                'name': 'Templeogue College',
                'principal_name': 'Mr. Tom Cunningham',
                'email': 'info@templeogue.ie',
                'phone': '01 490 3142',
                'address': 'Templeogue Road, Dublin 6W',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.templeogue.ie',
            },
            {
                'name': 'Pobalscoil Neasáin',
                'principal_name': 'Pádraig Ó Dufaigh',
                'email': 'oifig@pobalscoilneasain.ie',
                'phone': '01 847 0022',
                'address': 'Baldoyle, Dublin 13',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.pobalscoilneasain.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'St Fintan\'s High School',
                'principal_name': 'Mr. Paul Byrne',
                'email': 'info@fintans.swords.ie',
                'phone': '01 840 5736',
                'address': 'Swords, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stfintanshighschool.ie',
            },
            {
                'name': 'Skerries Community College',
                'principal_name': 'Ms. Jane O\'Connor',
                'email': 'info@skerriescc.ie',
                'phone': '01 849 1328',
                'address': 'Skerries, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.skerriescc.ie',
            },
            {
                'name': 'Portmarnock Community School',
                'principal_name': 'Mr. John Rowan',
                'email': 'info@portmarnockcs.ie',
                'phone': '01 846 0200',
                'address': 'Carrickhill Road, Portmarnock, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.portmarnockcs.ie',
            },
            {
                'name': 'St Paul\'s College Raheny',
                'principal_name': 'Mr. David O\'Callaghan',
                'email': 'info@stpaulsraheny.ie',
                'phone': '01 831 2167',
                'address': 'Raheny, Dublin 5',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stpaulsraheny.ie',
            },
            {
                'name': 'Kilkenny College',
                'principal_name': 'Mr. John Brennan',
                'email': 'info@kilkennycollege.ie',
                'phone': '056 776 1144',
                'address': 'Kilkenny',
                'county': 'Kilkenny',
                'school_type': 'secondary',
                'website': 'https://www.kilkennycollege.ie',
            },
            {
                'name': 'Loreto Secondary School Kilkenny',
                'principal_name': 'Ms. Ann Walsh',
                'email': 'info@loretokilkenny.ie',
                'phone': '056 772 1402',
                'address': 'Kilkenny',
                'county': 'Kilkenny',
                'school_type': 'secondary',
                'website': 'https://www.loretokilkenny.ie',
            },
            {
                'name': 'Grennan College Thomastown',
                'principal_name': 'Ms. Christina Kavanagh',
                'email': 'info@grennancollege.ie',
                'phone': '056 772 4184',
                'address': 'Thomastown, Co. Kilkenny',
                'county': 'Kilkenny',
                'school_type': 'community',
                'website': 'https://www.grennancollege.ie',
            },
            {
                'name': 'Presentation Secondary School Tralee',
                'principal_name': 'Mr. Patrick Sheahan',
                'email': 'office@presentationtralee.ie',
                'phone': '066 712 2041',
                'address': 'Moyderwell, Tralee, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'secondary',
                'website': 'https://www.presentationtralee.ie',
            },
            {
                'name': 'St Brendan\'s College Killarney',
                'principal_name': 'Mr. Denis Courtney',
                'email': 'office@stbrendanskillarney.com',
                'phone': '064 663 1008',
                'address': 'Killarney, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'secondary',
                'website': 'https://www.stbrendanskillarney.com',
            },
            {
                'name': 'Intermediate School Killorglin',
                'principal_name': 'Mr. Denis Courtney',
                'email': 'info@iskillorglin.ie',
                'phone': '066 976 1127',
                'address': 'Killorglin, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'secondary',
                'website': 'https://www.iskillorglin.ie',
            },
            {
                'name': 'Coláiste na Sceilge Cahersiveen',
                'principal_name': 'Mr. Barry O\'Sullivan',
                'email': 'info@colaistesceilge.ie',
                'phone': '066 947 2250',
                'address': 'Cahersiveen, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'community',
                'website': 'https://www.colaistesceilge.ie',
            },
            {
                'name': 'St Augustine\'s College Dungarvan',
                'principal_name': 'Mr. Tom Doocey',
                'email': 'staugustinescollege@eircom.net',
                'phone': '058 41203',
                'address': 'Dungarvan, Co. Waterford',
                'county': 'Waterford',
                'school_type': 'secondary',
                'website': 'https://www.staugustinescollege.ie',
            },
            {
                'name': 'Blackwater Community School Lismore',
                'principal_name': 'Mr. Liam O\'Sullivan',
                'email': 'office@blackwatercs.ie',
                'phone': '058 54177',
                'address': 'Lismore, Co. Waterford',
                'county': 'Waterford',
                'school_type': 'community',
                'website': 'https://www.blackwatercs.ie',
            },
            {
                'name': 'St Paul\'s Community College Waterford',
                'principal_name': 'Ms. Marie Breen',
                'email': 'info@stpaulscc.ie',
                'phone': '051 378 965',
                'address': 'Lisduggan, Waterford',
                'county': 'Waterford',
                'school_type': 'community',
                'website': 'https://www.stpaulscc.ie',
            },
            {
                'name': 'Enniscorthy Vocational College',
                'principal_name': 'Mr. Kieran Madden',
                'email': 'admin@evc.ie',
                'phone': '053 923 3666',
                'address': 'Shannon Park, Enniscorthy, Co. Wexford',
                'county': 'Wexford',
                'school_type': 'vocational',
                'website': 'https://www.evc.ie',
            },
            {
                'name': 'St Peter\'s College Wexford',
                'principal_name': 'Mr. Liam Lynch',
                'email': 'info@stpeterscollege.ie',
                'phone': '053 912 2320',
                'address': 'Summerhill, Wexford',
                'county': 'Wexford',
                'school_type': 'secondary',
                'website': 'https://www.stpeterscollege.ie',
            },
            {
                'name': 'Gorey Community School',
                'principal_name': 'Mr. Pat Murphy',
                'email': 'info@goreycs.ie',
                'phone': '053 942 1185',
                'address': 'Gorey, Co. Wexford',
                'county': 'Wexford',
                'school_type': 'community',
                'website': 'https://www.goreycs.ie',
            },
            {
                'name': 'Loreto Secondary School Wexford',
                'principal_name': 'Ms. Bernie Scallan',
                'email': 'loretosec@eircom.net',
                'phone': '053 912 2551',
                'address': 'Spawell Road, Wexford',
                'county': 'Wexford',
                'school_type': 'secondary',
                'website': 'https://www.loretowexford.ie',
            },
            {
                'name': 'New Ross CBS',
                'principal_name': 'Mr. Joseph Power',
                'email': 'admin@newrosscbs.ie',
                'phone': '051 421 162',
                'address': 'New Ross, Co. Wexford',
                'county': 'Wexford',
                'school_type': 'secondary',
                'website': 'https://www.newrosscbs.ie',
            },
            {
                'name': 'Coláiste Mhuire Mullingar',
                'principal_name': 'Mr. Paul Higgins',
                'email': 'info@colaiste-mhuire.ie',
                'phone': '044 934 0025',
                'address': 'Mullingar, Co. Westmeath',
                'county': 'Westmeath',
                'school_type': 'secondary',
                'website': 'https://www.colaiste-mhuire.ie',
            },
            {
                'name': 'Loreto College Mullingar',
                'principal_name': 'Ms. Ursula Coffey',
                'email': 'info@loretomullingar.ie',
                'phone': '044 934 3543',
                'address': 'Mullingar, Co. Westmeath',
                'county': 'Westmeath',
                'school_type': 'secondary',
                'website': 'https://www.loretomullingar.ie',
            },
            {
                'name': 'Wilson\'s Hospital School',
                'principal_name': 'Mr. Richard Tempany',
                'email': 'info@wilsonshospitalschool.com',
                'phone': '044 966 1808',
                'address': 'Multyfarnham, Co. Westmeath',
                'county': 'Westmeath',
                'school_type': 'secondary',
                'website': 'https://www.wilsonshospitalschool.com',
            },
            {
                'name': 'St Joseph\'s College Borrisokane',
                'principal_name': 'Mr. Liam McGrath',
                'email': 'info@stjosephsborrisokane.ie',
                'phone': '067 27105',
                'address': 'Borrisokane, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.stjosephsborrisokane.ie',
            },
            {
                'name': 'Nenagh College',
                'principal_name': 'Mr. John Bourke',
                'email': 'info@nenaghcollege.ie',
                'phone': '067 31326',
                'address': 'Nenagh, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'community',
                'website': 'https://www.nenaghcollege.ie',
            },
            {
                'name': 'Thurles CBS',
                'principal_name': 'Mr. Tom Clarke',
                'email': 'office@thurlescbs.ie',
                'phone': '0504 21371',
                'address': 'Thurles, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.thurlescbs.ie',
            },
            {
                'name': 'Ursuline Secondary School Thurles',
                'principal_name': 'Ms. Mary Butler',
                'email': 'info@ursulinethurles.ie',
                'phone': '0504 22238',
                'address': 'Thurles, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.ursulinethurles.ie',
            },
            {
                'name': 'Our Lady\'s Secondary School Templemore',
                'principal_name': 'Ms. Anne McGrath',
                'email': 'info@olsstemplemore.ie',
                'phone': '0504 31342',
                'address': 'Templemore, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.olsstemplemore.ie',
            },
            {
                'name': 'Coláiste Phobal Ros Cré',
                'principal_name': 'Mr. Pat O\'Meara',
                'email': 'info@cprc.ie',
                'phone': '0505 21027',
                'address': 'Roscrea, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'community',
                'website': 'https://www.cprc.ie',
            },
            {
                'name': 'St Mary\'s Secondary School Nenagh',
                'principal_name': 'Ms. Deirdre O\'Donnell',
                'email': 'office@stmarysnenagh.ie',
                'phone': '067 31382',
                'address': 'Nenagh, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.stmarysnenagh.ie',
            },
            {
                'name': 'Naas Community College',
                'principal_name': 'Mr. Johnny Nevin',
                'email': 'info@naascc.ie',
                'phone': '045 879 668',
                'address': 'Naas, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'community',
                'website': 'https://www.naascc.ie',
            },
            {
                'name': 'St Mary\'s College Naas',
                'principal_name': 'Ms. Catherine Drea',
                'email': 'admin@stmarysnaas.ie',
                'phone': '045 897 110',
                'address': 'Naas, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'secondary',
                'website': 'https://www.stmarysnaas.ie',
            },
            {
                'name': 'Maynooth Post Primary School',
                'principal_name': 'Mr. Richard O\'Toole',
                'email': 'info@maynoothpp.ie',
                'phone': '01 628 6060',
                'address': 'Maynooth, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'community',
                'website': 'https://www.maynoothpp.ie',
            },
            {
                'name': 'St Patrick\'s Classical School Navan',
                'principal_name': 'Mr. Paul Moynagh',
                'email': 'info@stpatsnavan.ie',
                'phone': '046 902 1222',
                'address': 'Navan, Co. Meath',
                'county': 'Meath',
                'school_type': 'secondary',
                'website': 'https://www.stpatsnavan.ie',
            },
            {
                'name': 'Beaufort College Navan',
                'principal_name': 'Mr. Alan Craven',
                'email': 'info@beaufortcollege.ie',
                'phone': '046 906 7100',
                'address': 'Navan, Co. Meath',
                'county': 'Meath',
                'school_type': 'community',
                'website': 'https://www.beaufortcollege.ie',
            },
            {
                'name': 'Mercy Secondary School Navan',
                'principal_name': 'Ms. Rosaleen Mulligan',
                'email': 'info@mercynavan.ie',
                'phone': '046 902 1258',
                'address': 'Navan, Co. Meath',
                'county': 'Meath',
                'school_type': 'secondary',
                'website': 'https://www.mercynavan.ie',
            },
            {
                'name': 'Dunshaughlin Community College',
                'principal_name': 'Mr. John Murphy',
                'email': 'info@dunshaughlincc.ie',
                'phone': '01 825 0344',
                'address': 'Dunshaughlin, Co. Meath',
                'county': 'Meath',
                'school_type': 'community',
                'website': 'https://www.dunshaughlincc.ie',
            },
            {
                'name': 'St Joseph\'s Secondary School Navan',
                'principal_name': 'Ms. Breda Matthews',
                'email': 'info@stjosephsnavan.ie',
                'phone': '046 902 1534',
                'address': 'Navan, Co. Meath',
                'county': 'Meath',
                'school_type': 'secondary',
                'website': 'https://www.stjosephsnavan.ie',
            },
        ]

        created_count = 0
        skipped_count = 0

        for school_data in schools_data:
            # Only create if school doesn't exist - never update existing schools
            school, created = School.objects.get_or_create(
                name=school_data['name'],
                defaults=school_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"✓ Created: {school.name}")
                )
            else:
                skipped_count += 1
                self.stdout.write(
                    self.style.WARNING(f"⊘ Skipped (already exists): {school.name}")
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"\n{'='*50}\n"
                f"Summary:\n"
                f"  Created: {created_count} schools\n"
                f"  Skipped (already exist): {skipped_count} schools\n"
                f"  Total: {School.objects.count()} schools in database\n"
                f"{'='*50}"
            )
        )