"""
Management command to seed initial school contact data.
Usage: python manage.py seed_schools
"""

from django.core.management.base import BaseCommand
from schools.models import School


class Command(BaseCommand):
    help = 'Seeds the database with initial school contact information'

    def handle(self, *args, **options):
        """Populate database with initial school data from research."""

        schools_data = [
            {
                'name': 'Newbridge College',
                'principal_name': 'Mr. Patrick O\'Brien',
                'email': 'info@newbridge-college.ie',
                'phone': '+353 45 487200',
                'address': 'Newbridge, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'secondary',
                'website': 'https://www.newbridgecollege.ie',
            },
            {
                'name': 'Blackrock College',
                'principal_name': 'Ms. Yvonne Markey',
                'email': 'info@blackrockcollege.com',
                'phone': '+353 1 275 2100',
                'address': 'Rock Road, Blackrock, Co. Dublin A94 FK84',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.blackrockcollege.com',
            },
            {
                'name': 'Castleknock College',
                'principal_name': 'Miss Elaine Kelly',
                'email': 'principalpa@castleknockcollege.ie',
                'phone': '',
                'address': 'Castleknock, Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.castleknockcollege.ie',
            },
            {
                'name': 'Coláiste Íosagáin',
                'principal_name': 'Treasa Ní Fhearraigh',
                'email': 'eolas@eoiniosagain.ie',
                'phone': '',
                'address': 'Stillorgan Road, Booterstown, Blackrock, Co. Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': '',
                'is_gaelscoil': True,
            },
            {
                'name': 'Christian Brothers College Cork',
                'principal_name': 'Mr. David Lordon',
                'email': 'enquire@cbccork.ie',
                'phone': '0214501653',
                'address': 'Sidney Hill, Wellington Road, Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.cbccork.ie',
            },
            {
                'name': 'Presentation Brothers College Cork',
                'principal_name': 'Mr. David Barry',
                'email': 'info@pbc-cork.ie',
                'phone': '021-4272743',
                'address': 'The Mardyke, Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.pbc-cork.ie',
            },
            {
                'name': 'Cork Educate Together Secondary School',
                'principal_name': 'Mr. Colm O\'Connor',
                'email': 'info@cetsl.ie',
                'phone': '',
                'address': 'Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'http://www.cetsl.ie',
            },
            {
                'name': 'St. Munchin\'s College',
                'principal_name': 'Mr. Shane Fitzgerald',
                'email': 'office@stmunchinscollege.ie',
                'phone': '061348922',
                'address': 'Corbally, Limerick',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'http://www.stmunchinscollege.com',
            },
            {
                'name': 'Ardscoil Rís Limerick',
                'principal_name': 'Mr. Tom Prendergast',
                'email': 'asroffice@eircom.net',
                'phone': '061-453828',
                'address': 'North Circular Road, Limerick V94 V602',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'https://www.ardscoil.com',
            },
            {
                'name': 'Coláiste Chiaráin Athlone',
                'principal_name': 'Mr. Brendan Waldron',
                'email': 'info@ccathlone.ie',
                'phone': '090 6492383',
                'address': 'Summerhill, Athlone, Co. Roscommon',
                'county': 'Roscommon',
                'school_type': 'secondary',
                'website': 'https://www.ccathlone.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'St Kieran\'s College Kilkenny',
                'principal_name': 'Mr. Adrian Finan',
                'email': 'school@stkieranscollege.ie',
                'phone': '0567761707',
                'address': 'College Road, Kilkenny',
                'county': 'Kilkenny',
                'school_type': 'secondary',
                'website': 'https://www.stkieranscollege.ie',
            },
            {
                'name': 'Galway City & Oranmore Educate Together Secondary School',
                'principal_name': 'Ms. Sarah Molloy',
                'email': 'admin@galwayetss.ie',
                'phone': '091 394262',
                'address': 'Newtownsmith, Galway City Centre, Galway',
                'county': 'Galway',
                'school_type': 'secondary',
                'website': 'https://galwayetss.ie',
            },
            {
                'name': 'Loreto College St Stephen\'s Green',
                'principal_name': 'Ms. Jacqueline Dempsey',
                'email': 'info@loretothegreen.ie',
                'phone': '016618179',
                'address': '53 St Stephens Green Dublin 2',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretothegreen.ie',
            },
            {
                'name': 'Gonzaga College',
                'principal_name': 'Mr. Damon McCaul',
                'email': 'headmaster@gonzaga.ie',
                'phone': '014972931',
                'address': 'Sandford Road, Ranelagh, Dublin 6',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': '',
            },
            {
                'name': 'Coláiste Eoin Finglas',
                'principal_name': 'Neil Dunphy',
                'email': 'info@eoin.cdetb.ie',
                'phone': '018341426',
                'address': 'Cappagh Road, Finglas West, Dublin 11',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://colaisteeoin.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'St Andrew\'s College Dublin',
                'principal_name': 'Ms Louise Marshall',
                'email': 'information@st-andrews.ie',
                'phone': '',
                'address': 'Dublin',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.sac.ie',
            },
            {
                'name': 'Mercy Mounthawk Secondary School',
                'principal_name': 'Mr. Patrick Fleming',
                'email': 'admin@mercymounthawk.ie',
                'phone': '066 710 2550',
                'address': 'Mounthawk, Tralee, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'secondary',
                'website': 'https://mercymounthawk.ie',
            },
            {
                'name': 'Loreto Abbey Secondary School Dalkey',
                'principal_name': 'Mr. Robert Dunne',
                'email': 'principal@loretoabbeydalkey.ie',
                'phone': '012718900',
                'address': 'Loreto Avenue, Off Harbour Road, Dalkey, Co. Dublin A96 YC81',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretoabbeydalkey.com',
            },
            {
                'name': 'Coláiste Pobail Acla',
                'principal_name': 'Jason Ó Mongáin',
                'email': '[email protected]',
                'phone': '098 45139',
                'address': 'Polranny, Achill, Co. Mayo',
                'county': 'Mayo',
                'school_type': 'community',
                'website': 'https://colaistepobailacla.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Presentation Secondary School Waterford',
                'principal_name': 'Ms. Sally Ronayne',
                'email': 'principal@preswaterford.ie',
                'phone': '051376584',
                'address': 'Cannon Street, Waterford',
                'county': 'Waterford',
                'school_type': 'secondary',
                'website': 'https://www.presentationsecondarywaterford.ie',
            },
            {
                'name': 'Stanhope Secondary School',
                'principal_name': 'Mr. John O\'Brien',
                'email': 'info@stanhopesecondary.ie',
                'phone': '01-6710419',
                'address': 'Manor Street, Stoneybatter, Dublin 7, D07 YP03',
                'county': 'Dublin',
                'school_type': 'secondary',
                'roll_number': '60843Q',
                'website': 'https://stanhopesecondary.ie',
                'is_gaelscoil': False,
                'secondary_contact_name': 'S. Mulligan',
                'secondary_contact_role': 'Contact',
                'secondary_contact_email': 'smulligan@stanhopesecondary.ie',
            },
            # Additional 50 schools for outreach campaign
            {
                'name': 'Rockwell College',
                'principal_name': 'Mr. Dónal Ó Ceallaigh',
                'email': 'info@rockwellcollege.ie',
                'phone': '062 61444',
                'address': 'Cashel, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.rockwellcollege.ie',
            },
            {
                'name': 'Clongowes Wood College',
                'principal_name': 'Mr. Chris Lumb',
                'email': 'reception@clongowes.net',
                'phone': '045 868202',
                'address': 'Clane, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'secondary',
                'website': 'https://www.clongowes.net',
            },
            {
                'name': 'Belvedere College',
                'principal_name': 'Mr. Paul Meany',
                'email': 'info@belvedere.ie',
                'phone': '01 858 5800',
                'address': 'Great Denmark Street, Dublin 1',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.belvedere.ie',
            },
            {
                'name': 'St Michael\'s College',
                'principal_name': 'Mr. Paul Gilligan',
                'email': 'office@stmichaelscollege.ie',
                'phone': '01 269 1003',
                'address': 'Ailesbury Road, Dublin 4',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stmichaelscollege.ie',
            },
            {
                'name': 'Terenure College',
                'principal_name': 'Mr. Thomas Geraghty',
                'email': 'secretary@terenure.ie',
                'phone': '01 490 7507',
                'address': 'Templeogue Road, Dublin 6W',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.terenure.ie',
            },
            {
                'name': 'Coláiste Iognáid',
                'principal_name': 'Caitríona Ní Chualáin',
                'email': 'admin@colaisteiognaid.ie',
                'phone': '091 529 900',
                'address': 'Sea Road, Galway',
                'county': 'Galway',
                'school_type': 'secondary',
                'website': 'https://www.colaisteiognaid.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Cistercian College Roscrea',
                'principal_name': 'Mr. Tomás Ó Murchú',
                'email': 'info@ccr.ie',
                'phone': '0505 25344',
                'address': 'Mount St Joseph, Roscrea, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.ccr.ie',
            },
            {
                'name': 'St Columba\'s College',
                'principal_name': 'Ms. Pauline Dooley',
                'email': 'schooloffice@stcolumbas.ie',
                'phone': '01 490 6791',
                'address': 'Whitechurch, Dublin 16',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.stcolumbas.ie',
            },
            {
                'name': 'Sligo Grammar School',
                'principal_name': 'Mr. Brendan Finlay',
                'email': 'info@sligogrammar.ie',
                'phone': '071 916 1809',
                'address': 'The Mall, Sligo',
                'county': 'Sligo',
                'school_type': 'secondary',
                'website': 'https://www.sligogrammar.ie',
            },
            {
                'name': 'Wesley College Dublin',
                'principal_name': 'Mr. Dermot Dunne',
                'email': 'info@wesleycollege.ie',
                'phone': '01 495 3900',
                'address': 'Ballinteer, Dublin 16',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.wesleycollege.ie',
            },
            {
                'name': 'Synge Street CBS',
                'principal_name': 'Mr. Brendan Farrell',
                'email': 'info@syngestreet.ie',
                'phone': '01 453 3737',
                'address': 'Synge Street, Dublin 8',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.syngestreet.ie',
            },
            {
                'name': 'Muckross Park College',
                'principal_name': 'Ms. Alison O\'Mahony',
                'email': 'info@muckrosspark.ie',
                'phone': '01 269 8844',
                'address': 'Marlborough Road, Donnybrook, Dublin 4',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.muckrosspark.ie',
            },
            {
                'name': 'Loreto College Foxrock',
                'principal_name': 'Ms. Ann Marie Mullen',
                'email': 'info@loretofoxrock.ie',
                'phone': '01 289 3042',
                'address': 'Foxrock, Dublin 18',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.loretofoxrock.ie',
            },
            {
                'name': 'Mount Anville Secondary School',
                'principal_name': 'Ms. Finola Kennedy',
                'email': 'office@mountanville.ie',
                'phone': '01 288 9364',
                'address': 'Mount Anville Road, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.mountanville.ie',
            },
            {
                'name': 'St Gerard\'s School Bray',
                'principal_name': 'Ms. Michelle McNiffe',
                'email': 'info@stgerardsbray.ie',
                'phone': '01 286 8991',
                'address': 'Bray, Co. Wicklow',
                'county': 'Wicklow',
                'school_type': 'secondary',
                'website': 'https://www.stgerardsbray.ie',
            },
            {
                'name': 'De La Salle College Waterford',
                'principal_name': 'Mr. John Gallagher',
                'email': 'info@delasallewaterford.com',
                'phone': '051 874385',
                'address': 'Newtown, Waterford',
                'county': 'Waterford',
                'school_type': 'secondary',
                'website': 'https://www.delasallewaterford.com',
            },
            {
                'name': 'Villiers School Limerick',
                'principal_name': 'Ms. Jill Storey',
                'email': 'office@villiers-school.com',
                'phone': '061 451447',
                'address': 'North Circular Road, Limerick',
                'county': 'Limerick',
                'school_type': 'secondary',
                'website': 'https://www.villiers-school.com',
            },
            {
                'name': 'Ursuline College Sligo',
                'principal_name': 'Ms. Attracta McKeon',
                'email': 'ursuline@eircom.net',
                'phone': '071 916 1790',
                'address': 'John Street, Sligo',
                'county': 'Sligo',
                'school_type': 'secondary',
                'website': 'https://www.ursulinecollege.ie',
            },
            {
                'name': 'Carrick-on-Suir CBS',
                'principal_name': 'Mr. David Nagle',
                'email': 'carrickonsuircbs@eircom.net',
                'phone': '051 640607',
                'address': 'Greenside, Carrick-on-Suir, Co. Tipperary',
                'county': 'Tipperary',
                'school_type': 'secondary',
                'website': 'https://www.carrickonsuircbs.com',
            },
            {
                'name': 'St Mary\'s College Dundalk',
                'principal_name': 'Mr. Noel Rodgers',
                'email': 'info@stmaryscollegedundalk.ie',
                'phone': '042 933 1670',
                'address': 'Dundalk, Co. Louth',
                'county': 'Louth',
                'school_type': 'secondary',
                'website': 'https://www.stmaryscollegedundalk.ie',
            },
            {
                'name': 'St Vincent\'s CBS Glasnevin',
                'principal_name': 'Mr. Frank Ruane',
                'email': 'office@vcbsglasnevin.ie',
                'phone': '01 837 9445',
                'address': 'St Vincent\'s Road, Glasnevin, Dublin 11',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.vcbsglasnevin.ie',
            },
            {
                'name': 'Ard Scoil na Mara Tramore',
                'principal_name': 'Ms. Siobhan Heffernan',
                'email': 'admin@asnamaratramore.ie',
                'phone': '051 381011',
                'address': 'Tramore, Co. Waterford',
                'county': 'Waterford',
                'school_type': 'community',
                'website': 'https://www.asnamaratramore.ie',
            },
            {
                'name': 'Moyle Park College',
                'principal_name': 'Ms. Linda Murphy',
                'email': 'office@moylepark.ie',
                'phone': '01 457 6565',
                'address': 'Clondalkin, Dublin 22',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.moylepark.ie',
            },
            {
                'name': 'Coláiste Mhuire Ennis',
                'principal_name': 'Mr. Fergal McDonagh',
                'email': 'cmcennis@eircom.net',
                'phone': '065 682 9710',
                'address': 'Harmony Row, Ennis, Co. Clare',
                'county': 'Clare',
                'school_type': 'secondary',
                'website': 'https://www.colaiste-mhuire.com',
            },
            {
                'name': 'St Flannan\'s College Ennis',
                'principal_name': 'Mr. John Hanly',
                'email': 'info@stflannans.ie',
                'phone': '065 682 8093',
                'address': 'Ennis, Co. Clare',
                'county': 'Clare',
                'school_type': 'secondary',
                'website': 'https://www.stflannans.ie',
            },
            {
                'name': 'Carlow Vocational School',
                'principal_name': 'Mr. Fergal O\'Neill',
                'email': 'admin@carlowvec.ie',
                'phone': '059 913 0977',
                'address': 'Kilkenny Road, Carlow',
                'county': 'Carlow',
                'school_type': 'vocational',
                'website': 'https://www.carlowvocationalschool.ie',
            },
            {
                'name': 'St Leo\'s College Carlow',
                'principal_name': 'Ms. Ann Marie Ahern',
                'email': 'office@stleoscarlow.ie',
                'phone': '059 914 2052',
                'address': 'Dublin Road, Carlow',
                'county': 'Carlow',
                'school_type': 'secondary',
                'website': 'https://www.stleoscarlow.ie',
            },
            {
                'name': 'Loreto College Cavan',
                'principal_name': 'Ms. Marie Hannon',
                'email': 'loretocavan@eircom.net',
                'phone': '049 433 1711',
                'address': 'Cavan',
                'county': 'Cavan',
                'school_type': 'secondary',
                'website': 'https://www.loretocavan.ie',
            },
            {
                'name': 'St Patrick\'s College Cavan',
                'principal_name': 'Mr. John Crowe',
                'email': 'info@stpatscavan.ie',
                'phone': '049 433 1044',
                'address': 'Cavan',
                'county': 'Cavan',
                'school_type': 'secondary',
                'website': 'https://www.stpatscavan.ie',
            },
            {
                'name': 'Pobalscoil Chorca Dhuibhne',
                'principal_name': 'Mairéad Uí Shé',
                'email': 'pobalscoil@eircom.net',
                'phone': '066 915 1034',
                'address': 'Dingle, Co. Kerry',
                'county': 'Kerry',
                'school_type': 'community',
                'website': 'https://www.pobalscoildingle.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Midleton College',
                'principal_name': 'Mr. William Halpin',
                'email': 'office@midletoncollege.ie',
                'phone': '021 463 1737',
                'address': 'Midleton, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.midletoncollege.ie',
            },
            {
                'name': 'St Brogan\'s College Bandon',
                'principal_name': 'Mr. Eoin Deasy',
                'email': 'office@stbrogans.ie',
                'phone': '023 884 1913',
                'address': 'Bandon, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.stbrogans.ie',
            },
            {
                'name': 'St Mary\'s Secondary School Mallow',
                'principal_name': 'Ms. Frances O\'Leary',
                'email': 'office@smsmallow.ie',
                'phone': '022 21366',
                'address': 'Mallow, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.smsmallow.ie',
            },
            {
                'name': 'Ashbourne Community School',
                'principal_name': 'Mr. Seán O\'Sullivan',
                'email': 'info@ashbournecs.ie',
                'phone': '01 835 0611',
                'address': 'Ashbourne, Co. Meath',
                'county': 'Meath',
                'school_type': 'community',
                'website': 'https://www.ashbournecs.ie',
            },
            {
                'name': 'Eureka Secondary School Kells',
                'principal_name': 'Ms. Therese O\'Brien',
                'email': 'eurekakells@eircom.net',
                'phone': '046 924 0233',
                'address': 'Kells, Co. Meath',
                'county': 'Meath',
                'school_type': 'secondary',
                'website': 'https://www.eurekakells.ie',
            },
            {
                'name': 'Tullamore College',
                'principal_name': 'Mr. Michael Cahill',
                'email': 'info@tullamorecollege.ie',
                'phone': '057 935 2474',
                'address': 'Tullamore, Co. Offaly',
                'county': 'Offaly',
                'school_type': 'community',
                'website': 'https://www.tullamorecollege.ie',
            },
            {
                'name': 'Coláiste Choilm Ballincollig',
                'principal_name': 'Mr. William O\'Shea',
                'email': 'office@colaistechoilm.ie',
                'phone': '021 487 1447',
                'address': 'Ballincollig, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.colaistechoilm.ie',
            },
            {
                'name': 'Coláiste na Toirbhirte Bandon',
                'principal_name': 'Mr. William Morrissey',
                'email': 'office@toirbhirtebandon.ie',
                'phone': '023 884 1713',
                'address': 'Bandon, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.toirbhirtebandon.ie',
            },
            {
                'name': 'Hazelwood College Dromcollogher',
                'principal_name': 'Mr. Patrick O\'Connor',
                'email': 'hazelwoodcollege@eircom.net',
                'phone': '063 83102',
                'address': 'Dromcollogher, Co. Limerick',
                'county': 'Limerick',
                'school_type': 'community',
                'website': 'https://www.hazelwoodcollege.ie',
            },
            {
                'name': 'St Nessan\'s Community College Moate',
                'principal_name': 'Ms. Mairead Fox',
                'email': 'info@stnessans.ie',
                'phone': '090 648 1076',
                'address': 'Moate, Co. Westmeath',
                'county': 'Westmeath',
                'school_type': 'community',
                'website': 'https://www.stnessans.ie',
            },
            {
                'name': 'St Aidan\'s Comprehensive School Cootehill',
                'principal_name': 'Mr. Colm Ryan',
                'email': 'info@staidanscootehill.ie',
                'phone': '049 555 2142',
                'address': 'Cootehill, Co. Cavan',
                'county': 'Cavan',
                'school_type': 'comprehensive',
                'website': 'https://www.staidanscootehill.ie',
            },
            {
                'name': 'Coláiste Pobail Setanta',
                'principal_name': 'Seán Ó Lideadha',
                'email': 'setanta@cpsetanta.ie',
                'phone': '01 848 0433',
                'address': 'Pembroke Cottages, Dublin 4',
                'county': 'Dublin',
                'school_type': 'community',
                'website': 'https://www.cpsetanta.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Coláiste de hÍde Tallaght',
                'principal_name': 'Máire Uí Fhearraigh',
                'email': 'office@colaistdehide.ie',
                'phone': '01 451 5741',
                'address': 'Tallaght, Dublin 24',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.colaistdehide.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Ashfield College Dublin',
                'principal_name': 'Mr. David Boyd',
                'email': 'info@ashfield.ie',
                'phone': '01 475 5877',
                'address': 'Dundrum, Dublin 14',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.ashfield.ie',
            },
            {
                'name': 'Coláiste Éanna Cabra',
                'principal_name': 'Caitríona Ní Cheallaigh',
                'email': 'info@colaisteeanna.ie',
                'phone': '01 838 3615',
                'address': 'Cabra, Dublin 7',
                'county': 'Dublin',
                'school_type': 'secondary',
                'website': 'https://www.colaisteeanna.ie',
                'is_gaelscoil': True,
            },
            {
                'name': 'Holy Family Community School Newbridge',
                'principal_name': 'Mr. Tom O\'Reilly',
                'email': 'office@holyfamilynewbridge.ie',
                'phone': '045 431 931',
                'address': 'Newbridge, Co. Kildare',
                'county': 'Kildare',
                'school_type': 'community',
                'website': 'https://www.holyfamilynewbridge.ie',
            },
            {
                'name': 'St Mary\'s Secondary School Macroom',
                'principal_name': 'Ms. Ann Hennessy',
                'email': 'admin@stmarymacroom.ie',
                'phone': '026 41130',
                'address': 'Macroom, Co. Cork',
                'county': 'Cork',
                'school_type': 'secondary',
                'website': 'https://www.stmarysmacroom.ie',
            },
            {
                'name': 'Ballymakenny College Drogheda',
                'principal_name': 'Mr. Derek Sheridan',
                'email': 'office@ballymakennycollege.ie',
                'phone': '041 983 8272',
                'address': 'Drogheda, Co. Louth',
                'county': 'Louth',
                'school_type': 'community',
                'website': 'https://www.ballymakennycollege.ie',
            },
            {
                'name': 'St Joseph\'s Secondary School Drogheda',
                'principal_name': 'Ms. Catherine King',
                'email': 'stjosephsrogheda@eircom.net',
                'phone': '041 983 8671',
                'address': 'Drogheda, Co. Louth',
                'county': 'Louth',
                'school_type': 'secondary',
                'website': 'https://www.stjosephsdrogheda.ie',
            },
        ]

        created_count = 0
        skipped_count = 0

        for school_data in schools_data:
            # Only create if school doesn't exist - never update existing schools
            school, created = School.objects.get_or_create(
                name=school_data['name'],
                defaults=school_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"✓ Created: {school.name}")
                )
            else:
                skipped_count += 1
                self.stdout.write(
                    self.style.WARNING(f"⊘ Skipped (already exists): {school.name}")
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"\n{'='*50}\n"
                f"Summary:\n"
                f"  Created: {created_count} schools\n"
                f"  Skipped (already exist): {skipped_count} schools\n"
                f"  Total: {School.objects.count()} schools in database\n"
                f"{'='*50}"
            )
        )