# Generated by Django 5.2.7 on 2025-11-24 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_lessons', '0014_questionpart_solution_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the cheat sheet', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Optional description of what's covered in this cheat sheet", null=True)),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='cheatsheets/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(help_text='Topic this cheat sheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cheatsheets', to='interactive_lessons.topic')),
            ],
            options={
                'verbose_name': 'Cheat Sheet',
                'verbose_name_plural': 'Cheat Sheets',
                'ordering': ['topic__name', 'order', 'title'],
            },
        ),
    ]
