# Generated by Django 5.2.17 on 2026-10-04 10:17

from django.db import migrations, models


def classify_existing(apps, schema_editor):
    """The per-topic notes PDFs were titled "Full Notes"; they are the Summary
    Notes now. The Log Tables booklet is a reference, not a cheat sheet."""
    CheatSheet = apps.get_model('cheatsheets', 'CheatSheet')
    CheatSheet.objects.filter(title='Full Notes').update(
        kind='summary_notes', title='Summary Notes'
    )
    CheatSheet.objects.filter(
        title__icontains='log', pdf_file__icontains='logtables'
    ).update(kind='reference')


def unclassify(apps, schema_editor):
    CheatSheet = apps.get_model('cheatsheets', 'CheatSheet')
    CheatSheet.objects.filter(kind='summary_notes', title='Summary Notes').update(
        title='Full Notes'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='kind',
            field=models.CharField(choices=[('summary_notes', 'Summary Notes'), ('cheat_sheet', 'Cheat Sheet'), ('reference', 'Reference')], db_index=True, default='cheat_sheet', help_text='Summary Notes and Cheat Sheets are listed on separate pages; Reference (the Log Tables booklet) is listed on neither', max_length=20),
        ),
        migrations.RunPython(classify_existing, unclassify),
    ]
