# Generated by Django 5.2.7 on 2026-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the school', max_length=200)),
                ('principal_name', models.CharField(help_text="Principal's full name", max_length=200)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='School website URL')),
                ('address', models.TextField(blank=True, help_text='Full postal address')),
                ('county', models.CharField(blank=True, help_text='County location', max_length=100)),
                ('school_type', models.CharField(choices=[('secondary', 'Secondary School'), ('community', 'Community College'), ('vocational', 'Vocational School'), ('comprehensive', 'Comprehensive School'), ('etb', 'ETB School')], default='secondary', help_text='Type of school', max_length=50)),
                ('roll_number', models.CharField(blank=True, help_text='Department of Education roll number', max_length=20)),
                ('initial_email_sent', models.DateTimeField(blank=True, help_text='When the initial outreach email was sent', null=True)),
                ('response_received', models.BooleanField(default=False, help_text='Has the school responded to our outreach?')),
                ('response_date', models.DateTimeField(blank=True, help_text='When we received a response', null=True)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Does this contact need a follow-up?')),
                ('follow_up_date', models.DateField(blank=True, help_text='Scheduled follow-up date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about communication with this school')),
                ('interested', models.BooleanField(default=False, help_text='School expressed interest in NumScoil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['county', 'name'],
            },
        ),
    ]
