# Generated by Django 5.2.7 on 2026-01-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('initial', 'Initial Outreach'), ('follow_up', 'Follow-up'), ('reminder', 'Reminder'), ('custom', 'Custom')], default='initial', help_text='Type of outreach email', max_length=20)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('body_text', models.TextField(help_text='Plain text version of email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML version of email body')),
                ('sent_to', models.EmailField(help_text='Email address this was sent to', max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the email was sent')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', help_text='Email delivery status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(help_text='School this email was sent to', on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='schools.school')),
                ('sent_by', models.ForeignKey(help_text='User who sent this email', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
