# Generated by Django 5.2.7 on 2026-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_gaelscoil',
            field=models.BooleanField(default=False, help_text='Is this an Irish-speaking school (Gaelscoil)?'),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_contact_email',
            field=models.EmailField(blank=True, help_text='Email for secondary contact (if different from principal)', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_contact_name',
            field=models.CharField(blank=True, help_text='Name of maths teacher, career guidance counsellor, or other contact', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_contact_role',
            field=models.CharField(blank=True, help_text="Role/position (e.g., 'Maths Teacher', 'Career Guidance Counsellor')", max_length=100),
        ),
    ]
