# Generated by Django 5.2.7 on 2026-09-01 18:33

import django.db.models.deletion
import django.utils.timezone
import homework_check.models
import students.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0011_alter_homeworktask_task_type'),
        ('hw_solutions', '0002_hwsolution_page_count_hwsolutionpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text="What the class calls this piece of work, e.g. 'Ex 5A Q1-8'", max_length=200)),
                ('solution_pages', models.CharField(blank=True, help_text="Pages of the solutions to use, e.g. '3-4'. Blank = all of them.", max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Awaiting photos'), ('analysing', 'Analysing'), ('complete', 'Complete'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('analysis', models.JSONField(blank=True, default=list)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('diagram_feedback', models.TextField(blank=True)),
                ('has_diagram', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10)),
                ('rating_reason', models.CharField(blank=True, help_text='Why no rating was given, when one was withheld.', max_length=200)),
                ('teacher_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=10)),
                ('teacher_note', models.TextField(blank=True, help_text="The teacher's own note, printed on the report.")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('readable', models.BooleanField(default=True)),
                ('confidence', models.CharField(blank=True, max_length=8)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('solution', models.ForeignKey(help_text='The worked solutions to compare against.', on_delete=django.db.models.deletion.PROTECT, related_name='homework_checks', to='hw_solutions.hwsolution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_checks', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_checks_given', to=settings.AUTH_USER_MODEL)),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_checks', to='homework.teacherclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Private: served only via the check_photo view, never by URL.', storage=students.storage.PrivateStorage(), upload_to=homework_check.models.check_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Not yet analysed'), ('analysed', 'Analysed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hw_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='homework_check.homeworkcheck')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='homeworkcheck',
            index=models.Index(fields=['teacher_class', '-created_at'], name='homework_ch_teacher_41ce9a_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkcheck',
            index=models.Index(fields=['student', '-created_at'], name='homework_ch_student_e9acba_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkcheck',
            index=models.Index(fields=['status'], name='homework_ch_status_70109b_idx'),
        ),
    ]
