# Generated by Django 5.2.17 on 2026-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkcheck',
            name='purge_after',
        ),
        migrations.AddField(
            model_name='homeworkcheck',
            name='photos_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworkcheck',
            name='photos_deleted_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
