# Generated by Django 5.2.17 on 2026-09-15 08:59

import django.db.models.deletion
import django.utils.timezone
import homework_check.models
import students.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_check', '0002_photos_deleted_keep_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, storage=students.storage.PrivateStorage(), upload_to=homework_check.models.scan_file_path)),
                ('thumbnail', models.ImageField(blank=True, help_text="First page, so the teacher can read the student's name.", storage=students.storage.PrivateStorage(), upload_to=homework_check.models.scan_file_path)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.CharField(blank=True, max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['received_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ScanAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=homework_check.models._new_token, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
