# Generated by Django 5.2.17 on 2026-09-15 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_check', '0003_scans_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('hw_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_usage', to='homework_check.homeworkcheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
