# Generated by Django 5.2.7 on 2025-10-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional image upload for this question.', null=True, upload_to='question_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
            ],
            options={
                'ordering': ('topic__name', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label for this part, e.g. (a), (b), (c)', max_length=10)),
                ('prompt', models.TextField(help_text='Text for this part of the question.')),
                ('answer', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('expected_type', models.CharField(choices=[('exact', 'Exact match'), ('numeric', 'Numeric'), ('expression', 'Algebraic Expression'), ('multi', 'Multiple choice')], default='exact', max_length=20)),
                ('scale', models.CharField(blank=True, max_length=10, null=True)),
                ('max_marks', models.PositiveIntegerField(default=0)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='interactive_lessons.question')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=10)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='interactive_lessons.question')),
            ],
            options={
                'db_table': 'interactive_lessons_subquestion',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interactive_lessons.topic'),
        ),
    ]
