# Generated by Django 5.2.7 on 2025-10-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubQuestion',
        ),
    ]
