# Generated by Django 5.2.7 on 2025-10-18 12:14

from django.db import migrations


def migrate_questions_to_parts(apps, schema_editor):
    Question = apps.get_model('interactive_lessons', 'Question')
    QuestionPart = apps.get_model('interactive_lessons', 'QuestionPart')

    for question in Question.objects.all():
        # Only create a part if one doesn’t already exist
        if not QuestionPart.objects.filter(question=question).exists():
            QuestionPart.objects.create(
                question=question,
                label="(a)",
                prompt=question.text,
                answer=question.answer,
                hint=question.hint,
                solution=question.solution,
                order=1,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0002_delete_subquestion'),
    ]

    operations = [
        migrations.RunPython(migrate_questions_to_parts),
    ]
