# Generated by Django 5.2.7 on 2025-10-06 08:06

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0003_question_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
