# Generated by Django 5.2.7 on 2025-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0004_alter_question_answer_alter_question_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image to display below the question.', null=True),
        ),
    ]
