# Generated by Django 5.2.7 on 2025-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0004_remove_question_answer_remove_question_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Full worked solution for this question.', null=True),
        ),
    ]
