# Generated by Django 5.2.7 on 2025-10-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0005_question_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpart',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='questionpart',
            name='marks_awarded',
        ),
    ]
