# Generated by Django 5.2.7 on 2025-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0006_remove_questionpart_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this specific question part (e.g., diagram, graph).', null=True, upload_to='question_part_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Hint for this question (applies to all parts).', null=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='hint',
            field=models.TextField(blank=True, help_text='Expected format of the answer (e.g., decimal, fraction, degrees)', null=True, verbose_name='Expected format'),
        ),
    ]
