# Generated by Django 5.2.7 on 2025-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0007_questionpart_image_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpart',
            name='expected_type',
            field=models.CharField(choices=[('exact', 'Exact match'), ('numeric', 'Numeric'), ('expression', 'Algebraic Expression'), ('multi', 'Multiple choice'), ('manual', 'Manual grading required')], default='exact', max_length=20),
        ),
    ]
