# Generated by Django 5.2.7 on 2025-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0008_alter_questionpart_expected_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_year',
            field=models.IntegerField(blank=True, help_text='Year of the exam (e.g., 2024, 2023)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_exam_question',
            field=models.BooleanField(default=False, help_text='True if this is from an actual LC exam paper'),
        ),
        migrations.AddField(
            model_name='question',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('p1', 'Paper 1'), ('p2', 'Paper 2')], help_text='Paper 1 or Paper 2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_pdf_name',
            field=models.CharField(blank=True, help_text='Original PDF filename for reference', max_length=255, null=True),
        ),
    ]
