# Generated by Django 5.2.7 on 2025-11-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0009_question_exam_year_question_is_exam_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpart',
            old_name='hint',
            new_name='expected_format',
        ),
    ]
