# Generated by Django 5.2.7 on 2025-11-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0010_rename_hint_to_expected_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Hint for this question (applies to all parts).', null=True),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='expected_format',
            field=models.TextField(blank=True, help_text='Expected format of the answer (e.g., decimal, fraction, degrees)', null=True),
        ),
    ]
