# Generated by Django 5.2.7 on 2025-11-13 10:09

from django.db import migrations


def update_sections(apps, schema_editor):
    """Update sections for questions that were missing them."""
    Question = apps.get_model('interactive_lessons', 'Question')

    # Define section mappings based on content analysis
    section_updates = {
        # Algebra questions
        43: "Area Calculations",
        94: "Quadratic Equations - Discriminant",
        95: "Integration",

        # Descriptive Statistics
        26: "Histograms and Distributions",
        30: "Correlation and Regression",

        # Finance
        70: "Simple Interest",

        # Inferential Statistics
        72: "Central Limit Theorem",
        73: "Sampling Distribution",
        74: "Central Limit Theorem",
        75: "Confidence Intervals",
        76: "Confidence Intervals",
        77: "Confidence Intervals",
        78: "Confidence Intervals for Proportions",

        # Probability
        96: "Counting Principles",
        97: "Counting Principles",
        98: "Counting Principles",
        99: "Permutations",
        100: "Permutations with Restrictions",
        101: "Combinations",
        102: "Combinations with Restrictions",
        103: "Independent Events",
        104: "Compound Probability",
        105: "Combinations with Restrictions",
        106: "Probability Basics",
        107: "Probability Estimation",
        108: "Probability Rules",
        109: "Sample Space",
        110: "Sample Space",
        111: "Sample Space",
        112: "Expected Value",
        113: "Probability without Replacement",
        114: "Normal Distribution",
    }

    # Update each question
    for question_id, section in section_updates.items():
        try:
            question = Question.objects.get(id=question_id)
            question.section = section
            question.save()
        except Question.DoesNotExist:
            # Question might not exist in this database
            pass


def reverse_sections(apps, schema_editor):
    """Reverse the section updates (set back to null)."""
    Question = apps.get_model('interactive_lessons', 'Question')

    question_ids = [
        43, 94, 95, 26, 30, 70, 72, 73, 74, 75, 76, 77, 78,
        96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106,
        107, 108, 109, 110, 111, 112, 113, 114
    ]

    for question_id in question_ids:
        try:
            question = Question.objects.get(id=question_id)
            question.section = None
            question.save()
        except Question.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0011_rename_text_to_hint'),
    ]

    operations = [
        migrations.RunPython(update_sections, reverse_sections),
    ]
