# Generated by Django 5.2.8 on 2025-11-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive_lessons", "0012_update_question_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the inquiry", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Student's message")),
                ("topic_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "question_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        help_text="Teacher's reply to this inquiry",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unanswered", "Unanswered"),
                            ("answered", "Answered"),
                        ],
                        default="unanswered",
                        help_text="Whether this inquiry has been answered",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        help_text="Question this inquiry is about (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="interactive_lessons.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who sent this inquiry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Inquiry",
                "verbose_name_plural": "Student Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
