# Generated by Django 5.2.7 on 2025-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0013_studentinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='Optional solution image for this part (e.g., worked solution diagram)', null=True, upload_to='solutions/'),
        ),
    ]
