# Generated by Django 5.2.7 on 2025-11-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0014_questionpart_solution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_old',
            field=models.CharField(blank=True, help_text='DEPRECATED: Old text-based section field', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='interactive_lessons.topic')),
            ],
            options={
                'ordering': ('topic', 'order'),
                'unique_together': {('topic', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interactive_lessons.section'),
        ),
    ]
