# Generated by Django 5.2.7 on 2025-11-25 21:20

from django.db import migrations
from django.utils.text import slugify


def populate_sections(apps, schema_editor):
    """
    Create Section records from existing Question.section (CharField) data.
    Groups questions by topic and section name, creating ordered sections.

    NOTE: Skipped for fresh installations as the 'section' column was removed
    in a later migration. This only runs when migrating existing databases.
    """
    from django.db import connection

    # Check if the section column exists before trying to query it
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'interactive_lessons_question'
            AND COLUMN_NAME = 'section'
        """)
        column_exists = cursor.fetchone()[0] > 0

    if not column_exists:
        # Fresh installation - skip this migration
        print("Skipping section population (fresh installation)")
        return

    Section = apps.get_model('interactive_lessons', 'Section')
    Topic = apps.get_model('interactive_lessons', 'Topic')

    # Get all distinct (topic, section) pairs using raw SQL
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT DISTINCT topic_id, section
            FROM interactive_lessons_question
            WHERE section IS NOT NULL AND section != ''
            ORDER BY topic_id, section
        """)
        rows = cursor.fetchall()

    # Group by topic
    topic_sections = {}
    for topic_id, section_name in rows:
        if topic_id not in topic_sections:
            topic_sections[topic_id] = set()
        topic_sections[topic_id].add(section_name.strip())

    # Create Section records
    for topic_id, section_names in topic_sections.items():
        topic = Topic.objects.get(id=topic_id)

        # Sort section names alphabetically for consistent ordering
        for order, section_name in enumerate(sorted(section_names), start=1):
            # Create unique slug
            base_slug = slugify(f"{topic.name}-{section_name}")
            slug = base_slug[:255]  # Truncate to max length
            counter = 1
            while Section.objects.filter(slug=slug).exists():
                slug = f"{base_slug[:245]}-{counter}"[:255]  # Ensure max length
                counter += 1

            Section.objects.create(
                name=section_name,
                slug=slug,
                topic=topic,
                order=order * 10  # Use increments of 10 to allow easy reordering
            )

    print(f"Created {Section.objects.count()} sections")


def reverse_populate_sections(apps, schema_editor):
    """Remove all sections created by this migration."""
    Section = apps.get_model('interactive_lessons', 'Section')
    Section.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0015_add_section_model'),
    ]

    operations = [
        migrations.RunPython(populate_sections, reverse_populate_sections),
    ]
