# Generated by Django 5.2.7 on 2025-11-25 21:20

from django.db import migrations


def link_questions_to_sections(apps, schema_editor):
    """
    Link each Question to its Section based on the section (CharField) value.
    Uses raw SQL to avoid model conflicts during migration.

    NOTE: Skipped for fresh installations as the 'section' column was removed
    in a later migration. This only runs when migrating existing databases.
    """
    from django.db import connection

    # Check if the section column exists before trying to query it
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'interactive_lessons_question'
            AND COLUMN_NAME = 'section'
        """)
        column_exists = cursor.fetchone()[0] > 0

    if not column_exists:
        # Fresh installation - skip this migration
        print("Skipping question-section linking (fresh installation)")
        return

    Section = apps.get_model('interactive_lessons', 'Section')

    # Get question IDs and their section names
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, topic_id, section
            FROM interactive_lessons_question
            WHERE section IS NOT NULL AND section != ''
        """)
        questions = cursor.fetchall()

    linked_count = 0
    missing_count = 0

    for question_id, topic_id, section_name in questions:
        try:
            section = Section.objects.get(
                topic_id=topic_id,
                name=section_name.strip()
            )

            # Update the question with raw SQL
            with connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE interactive_lessons_question
                    SET section_id = %s
                    WHERE id = %s
                """, [section.id, question_id])

            linked_count += 1
        except Section.DoesNotExist:
            print(f"Warning: No section found for question {question_id}: "
                  f"topic_id={topic_id}, section='{section_name}'")
            missing_count += 1

    print(f"Linked {linked_count} questions to sections")
    if missing_count > 0:
        print(f"Warning: {missing_count} questions have no section")


def reverse_link(apps, schema_editor):
    """Unlink all questions from sections."""
    Question = apps.get_model('interactive_lessons', 'Question')
    Question.objects.all().update(section=None)


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0016_populate_sections'),
    ]

    operations = [
        migrations.RunPython(link_questions_to_sections, reverse_link),
    ]
