# Generated by Django 5.2.7 on 2025-11-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_papers', '0004_answerformattemplate_and_more'),
        ('interactive_lessons', '0017_link_questions_to_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='answer_format_template',
            field=models.ForeignKey(blank=True, help_text='Select a predefined answer format template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_papers.answerformattemplate'),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='expected_format',
            field=models.TextField(blank=True, help_text='Custom format description (or leave blank to use template)', null=True),
        ),
    ]
