# Generated by Django 5.2.7 on 2025-12-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_papers", "0008_examquestionpart_answer_format_template_and_more"),
        ("interactive_lessons", "0017_link_questions_to_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_copyrighted",
            field=models.BooleanField(
                default=False,
                help_text="True if this question is copyrighted (e.g., from published exam papers)",
            ),
        ),
        migrations.AddField(
            model_name="questionpart",
            name="answer_format_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a predefined answer format template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_papers.answerformattemplate",
            ),
        ),
        migrations.AddField(
            model_name="questionpart",
            name="solution_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional solution image for this part (e.g., worked solution diagram)",
                null=True,
                upload_to="solutions/",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_year",
            field=models.IntegerField(
                blank=True,
                help_text="DEPRECATED: Use exam_papers app instead. Year of the exam (e.g., 2024, 2023)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_exam_question",
            field=models.BooleanField(
                default=False,
                help_text="DEPRECATED: Use exam_papers app instead. True if this is from an actual LC exam paper",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="paper_type",
            field=models.CharField(
                blank=True,
                choices=[("p1", "Paper 1"), ("p2", "Paper 2")],
                help_text="DEPRECATED: Use exam_papers app instead. Paper 1 or Paper 2",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="source_pdf_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use exam_papers app instead. Original PDF filename for reference",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="questionpart",
            name="expected_format",
            field=models.TextField(
                blank=True,
                help_text="Custom format description (or leave blank to use template)",
                null=True,
            ),
        ),
    ]
