# Generated by Django 5.2.7 on 2025-12-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0018_question_is_copyrighted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='is_quickkick_suitable',
            field=models.BooleanField(default=False, help_text='Mark this question as suitable for QuickKick videos (shows in dropdown when adding test questions)'),
        ),
    ]
