# Generated by Django 5.2.7 on 2025-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0018_questionpart_answer_format_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_copyrighted',
            field=models.BooleanField(default=False, help_text='True if this question is copyrighted (e.g., from published exam papers)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_year',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Use exam_papers app instead. Year of the exam (e.g., 2024, 2023)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_exam_question',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use exam_papers app instead. True if this is from an actual LC exam paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('p1', 'Paper 1'), ('p2', 'Paper 2')], help_text='DEPRECATED: Use exam_papers app instead. Paper 1 or Paper 2', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_pdf_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use exam_papers app instead. Original PDF filename for reference', max_length=255, null=True),
        ),
    ]
