# Generated by Django 5.2.7 on 2025-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0019_questionpart_is_quickkick_suitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_quickkick_suitable',
            field=models.BooleanField(default=False, help_text='Mark this question as suitable for QuickKick videos (shows in dropdown when adding test questions)'),
        ),
    ]
