# Generated by Django 5.2.7 on 2025-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0020_question_is_quickkick_suitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpart',
            name='answer_format_template',
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='expected_format',
            field=models.TextField(blank=True, help_text='Custom format description', null=True),
        ),
    ]
