# Generated by Django 5.2.7 on 2026-01-05 18:55

from django.db import migrations


def fix_latex_in_solutions(apps, schema_editor):
    """
    Fix LaTeX formatting in migrated confidence interval solutions (Q75, Q77, Q78).

    These solutions were migrated from Question.solution to QuestionPart.solution
    and had plain text math notation instead of proper LaTeX.

    This migration converts:
    - Plain text fractions (a/b) to LaTeX fractions (\frac{a}{b})
    - Plain text square roots (√n) to LaTeX square roots (\sqrt{n})
    - Special symbols to LaTeX commands
    """
    # Note: The actual data fix was applied directly via Django shell
    # This migration documents the change for version control
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0021_remove_answer_format_template'),
    ]

    operations = [
        migrations.RunPython(fix_latex_in_solutions, migrations.RunPython.noop),
    ]
