# Generated by Django 5.2.7 on 2026-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0022_fix_latex_in_confidence_interval_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_quickkick_suitable',
            field=models.BooleanField(default=False, help_text='Mark this question as suitable for QuickFlicks videos (shows in dropdown when adding test questions)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use QuestionPart.solution instead. Full worked solution for this question.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use QuestionPart.solution_image instead.', null=True, upload_to='solutions/'),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='is_quickkick_suitable',
            field=models.BooleanField(default=False, help_text='Mark this question as suitable for QuickFlicks videos (shows in dropdown when adding test questions)'),
        ),
    ]
