# Generated by Django 5.2.7 on 2026-01-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0022_fix_latex_in_confidence_interval_solutions'),
        ('interactive_lessons', '0023_alter_question_is_quickkick_suitable_and_more'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]