# Generated by Django 5.2.7 on 2026-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0024_merge_20260116_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='solution_unlock_after_attempts',
            field=models.PositiveIntegerField(
                default=2,
                help_text='Number of attempts before solution becomes visible (0 = always visible, 2 = default for production)'
            ),
        ),
    ]