# Generated by Django 5.2.7 on 2026-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0025_questionpart_solution_unlock_after_attempts'),
    ]

    operations = [
        # Field already exists from migration 0025
        # This migration ensures local and production are in sync
    ]
