# Generated by Django 5.2.7 on 2026-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('interactive_lessons', '0026_add_solution_unlock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='solution_unlock_after_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Number of attempts before solution becomes visible (0 = always visible, 2 = default for production)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this topic belongs to (Maths, Physics, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.subject'),
        ),
    ]
