# Generated by Django 5.2.7 on 2026-01-26 20:18

from django.db import migrations


def assign_to_maths(apps, schema_editor):
    """
    Assign all existing Topics and ExamPapers to Maths subject.
    This ensures existing content is properly categorized before making subject required.
    """
    Subject = apps.get_model('core', 'Subject')
    Topic = apps.get_model('interactive_lessons', 'Topic')
    ExamPaper = apps.get_model('exam_papers', 'ExamPaper')

    # Get Maths subject
    try:
        maths = Subject.objects.get(slug='maths')
    except Subject.DoesNotExist:
        print("WARNING: Maths subject not found. Creating it...")
        maths = Subject.objects.create(
            name='Maths',
            slug='maths',
            display_order=1,
            is_active=True,
            icon='📐',
            description='Leaving Certificate Higher Level Mathematics'
        )

    # Assign all Topics without a subject to Maths
    topics_updated = Topic.objects.filter(subject__isnull=True).update(subject=maths)
    print(f"Assigned {topics_updated} topics to Maths")

    # Assign all ExamPapers without a subject to Maths
    papers_updated = ExamPaper.objects.filter(subject__isnull=True).update(subject=maths)
    print(f"Assigned {papers_updated} exam papers to Maths")


def reverse_assignment(apps, schema_editor):
    """Set all subjects back to NULL"""
    Topic = apps.get_model('interactive_lessons', 'Topic')
    ExamPaper = apps.get_model('exam_papers', 'ExamPaper')

    Topic.objects.all().update(subject=None)
    ExamPaper.objects.all().update(subject=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
        ('exam_papers', '0019_exampaper_subject'),
        ('interactive_lessons', '0027_questionpart_solution_unlock_after_attempts_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_to_maths, reverse_assignment),
    ]
