# Generated by Django 5.2.7 on 2026-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0029_questionpart_solution_unlock_after_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position within its paper. Equal values fall back to alphabetical, so leaving these all at 0 is the same as sorting by name.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='paper',
            field=models.CharField(blank=True, choices=[('p1', 'Paper 1'), ('p2', 'Paper 2')], help_text="Which exam paper this topic sits on. Leave blank for subjects without a paper split, or until it is decided - blank topics are still listed, under 'Other topics'.", max_length=2),
        ),
    ]
