# Generated by Django 5.2.17 on 2026-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0031_assign_topic_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='short_name',
            field=models.CharField(blank=True, help_text='Shown in the Exercises table instead of the full name, which then appears on hover. Leave blank to use the name.', max_length=40),
        ),
    ]
