# Generated by Django 5.2.7 on 2025-12-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactive_lessons', '0017_link_questions_to_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickKick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for the animation', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of what the animation covers')),
                ('video', models.FileField(help_text='Upload MP4 video file', upload_to='quickkicks/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within topic')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Video duration in seconds (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickkicks', to='interactive_lessons.topic')),
            ],
            options={
                'verbose_name': 'QuickKick Video',
                'verbose_name_plural': 'QuickKick Videos',
                'ordering': ('topic', 'order', 'title'),
            },
        ),
    ]
