# Generated by Django 5.2.7 on 2025-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickkicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickkick',
            options={'ordering': ('topic', 'order', 'title'), 'verbose_name': 'QuickKick', 'verbose_name_plural': 'QuickKicks'},
        ),
        migrations.AddField(
            model_name='quickkick',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video (MP4)'), ('geogebra', 'GeoGebra Applet')], default='video', help_text='Type of content: Video or GeoGebra applet', max_length=20),
        ),
        migrations.AddField(
            model_name='quickkick',
            name='geogebra_url',
            field=models.URLField(blank=True, help_text='GeoGebra applet URL (required if content type is GeoGebra)'),
        ),
        migrations.AlterField(
            model_name='quickkick',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this resource covers'),
        ),
        migrations.AlterField(
            model_name='quickkick',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Video duration in seconds (optional, only for videos)'),
        ),
        migrations.AlterField(
            model_name='quickkick',
            name='title',
            field=models.CharField(help_text='Display title for the resource', max_length=200),
        ),
        migrations.AlterField(
            model_name='quickkick',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 video file (required if content type is Video)', null=True, upload_to='quickkicks/'),
        ),
    ]
