# Generated by Django 5.2.7 on 2025-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickkicks', '0002_alter_quickkick_options_quickkick_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickkick',
            name='geogebra_url',
        ),
        migrations.AddField(
            model_name='quickkick',
            name='geogebra_code',
            field=models.CharField(blank=True, help_text="GeoGebra applet code (e.g., 'pvvcyzts') - required if content type is GeoGebra", max_length=50),
        ),
    ]
