# Generated by Django 5.2.7 on 2025-12-07 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickkicks', '0003_rename_geogebra_url_to_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickKickView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quickkick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='quickkicks.quickkick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickkick_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuickKick View',
                'verbose_name_plural': 'QuickKick Views',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'quickkick')},
            },
        ),
    ]
