# Generated by Django 5.2.7 on 2025-12-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0018_question_is_copyrighted_and_more'),
        ('quickkicks', '0004_quickkickview'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickkick',
            name='question_part',
            field=models.ForeignKey(blank=True, help_text='Optional question to test comprehension after watching (links to existing QuestionPart)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickkicks', to='interactive_lessons.questionpart'),
        ),
        migrations.AddField(
            model_name='quickkickview',
            name='answer_correct',
            field=models.BooleanField(default=False, help_text='Whether the submitted answer was correct'),
        ),
        migrations.AddField(
            model_name='quickkickview',
            name='answer_submitted',
            field=models.BooleanField(default=False, help_text='Whether student has submitted an answer to the test question'),
        ),
        migrations.AddField(
            model_name='quickkickview',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of attempts at the test question'),
        ),
        migrations.AddField(
            model_name='quickkickview',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, help_text='When the last answer attempt was made', null=True),
        ),
        migrations.AddField(
            model_name='quickkickview',
            name='score_awarded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score awarded (0-100) for the test question', max_digits=5),
        ),
    ]
