# Generated by Django 5.2.7 on 2025-12-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_lessons', '0020_question_is_quickkick_suitable'),
        ('quickkicks', '0005_quickkick_question_part_quickkickview_answer_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickkick',
            name='question_part',
        ),
        migrations.AddField(
            model_name='quickkick',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Optional question to test comprehension after watching (links to existing Question)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickkicks', to='interactive_lessons.question'),
        ),
    ]
