# Generated by Django 5.2.7 on 2026-01-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickkicks', '0006_remove_quickkick_question_part_quickkick_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickkick',
            options={'ordering': ('topic', 'order', 'title'), 'verbose_name': 'QuickFlicks', 'verbose_name_plural': 'QuickFlicks'},
        ),
        migrations.AlterModelOptions(
            name='quickkickview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'QuickFlicks View', 'verbose_name_plural': 'QuickFlicks Views'},
        ),
    ]
