# Generated by Django 5.2.7 on 2026-08-31 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the homework solution (e.g. 'Week 3 - Trigonometry')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional note about what this solution covers')),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='hw_solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject this belongs to. Leave blank to show it under every subject.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_solutions', to='core.subject')),
            ],
            options={
                'verbose_name': 'HW Solution',
                'verbose_name_plural': 'HW Solutions',
                'ordering': ['order', '-created_at', 'title'],
            },
        ),
    ]
