# Generated by Django 5.2.7 on 2026-09-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwsolution',
            name='page_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Filled in automatically the first time the pages are rendered.'),
        ),
        migrations.CreateModel(
            name='HWSolutionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='hw_solutions/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='hw_solutions.hwsolution')),
            ],
            options={
                'ordering': ['solution', 'page_number'],
                'constraints': [models.UniqueConstraint(fields=('solution', 'page_number'), name='uniq_hwsolutionpage_solution_page')],
            },
        ),
    ]
