# Generated by Django 5.2.7 on 2026-09-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_solutions', '0002_hwsolution_page_count_hwsolutionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWSolutionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Exercise 1.3'", max_length=100)),
                ('first_page', models.PositiveSmallIntegerField()),
                ('last_page', models.PositiveSmallIntegerField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hw_solutions.hwsolution')),
            ],
            options={
                'ordering': ['solution', 'first_page'],
                'constraints': [models.UniqueConstraint(fields=('solution', 'label'), name='uniq_hwsolutionsection_solution_label')],
            },
        ),
    ]
